-- =========================================================
-- ATOMDROPS DATABASE SCHEMA
-- Smart Multi-Vendor Marketplace
-- MariaDB 10.4+
-- =========================================================

CREATE DATABASE IF NOT EXISTS atomdb
  CHARACTER SET utf8mb4
  COLLATE utf8mb4_unicode_ci;

USE atomdb;

-- CORE: USERS & ROLES
CREATE TABLE IF NOT EXISTS roles (
  id BIGINT PRIMARY KEY AUTO_INCREMENT,
  name VARCHAR(50) NOT NULL UNIQUE
);

CREATE TABLE IF NOT EXISTS users (
  id BIGINT PRIMARY KEY AUTO_INCREMENT,
  email VARCHAR(191) NOT NULL UNIQUE,
  password_hash VARCHAR(255) NOT NULL,
  display_name VARCHAR(120) NOT NULL,
  phone VARCHAR(30),
  status ENUM('ACTIVE','SUSPENDED','BANNED') NOT NULL DEFAULT 'ACTIVE',
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NULL DEFAULT NULL ON UPDATE CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS user_roles (
  user_id BIGINT NOT NULL,
  role_id BIGINT NOT NULL,
  PRIMARY KEY (user_id, role_id),
  FOREIGN KEY (user_id) REFERENCES users(id),
  FOREIGN KEY (role_id) REFERENCES roles(id)
);

-- MARKETPLACE: CATEGORIES, PRODUCTS, INVENTORY
CREATE TABLE IF NOT EXISTS categories (
  id BIGINT PRIMARY KEY AUTO_INCREMENT,
  name VARCHAR(120) NOT NULL UNIQUE,
  parent_id BIGINT NULL,
  FOREIGN KEY (parent_id) REFERENCES categories(id)
);

CREATE TABLE IF NOT EXISTS products (
  id BIGINT PRIMARY KEY AUTO_INCREMENT,
  vendor_id BIGINT NOT NULL,
  category_id BIGINT NOT NULL,
  name VARCHAR(255) NOT NULL,
  description TEXT,
  price_bdt DECIMAL(12,2) NOT NULL,
  status ENUM('DRAFT','ACTIVE','INACTIVE','OUT_OF_STOCK') NOT NULL DEFAULT 'ACTIVE',
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NULL DEFAULT NULL ON UPDATE CURRENT_TIMESTAMP,
  FOREIGN KEY (vendor_id) REFERENCES users(id),
  FOREIGN KEY (category_id) REFERENCES categories(id)
);

CREATE TABLE IF NOT EXISTS product_images (
  id BIGINT PRIMARY KEY AUTO_INCREMENT,
  product_id BIGINT NOT NULL,
  image_url VARCHAR(500) NOT NULL,
  sort_order INT NOT NULL DEFAULT 0,
  FOREIGN KEY (product_id) REFERENCES products(id)
);

CREATE TABLE IF NOT EXISTS inventory (
  id BIGINT PRIMARY KEY AUTO_INCREMENT,
  product_id BIGINT NOT NULL UNIQUE,
  stock_qty INT NOT NULL DEFAULT 0,
  low_stock_threshold INT NOT NULL DEFAULT 5,
  FOREIGN KEY (product_id) REFERENCES products(id)
);

-- ORDERS & DUMMY PAYMENTS
CREATE TABLE IF NOT EXISTS orders (
  id BIGINT PRIMARY KEY AUTO_INCREMENT,
  customer_id BIGINT NOT NULL,
  total_bdt DECIMAL(12,2) NOT NULL,
  status ENUM('PLACED','PAID','SHIPPED','DELIVERED','CANCELLED') NOT NULL DEFAULT 'PLACED',
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  FOREIGN KEY (customer_id) REFERENCES users(id)
);

CREATE TABLE IF NOT EXISTS order_items (
  id BIGINT PRIMARY KEY AUTO_INCREMENT,
  order_id BIGINT NOT NULL,
  product_id BIGINT NOT NULL,
  qty INT NOT NULL,
  unit_price_bdt DECIMAL(12,2) NOT NULL,
  FOREIGN KEY (order_id) REFERENCES orders(id),
  FOREIGN KEY (product_id) REFERENCES products(id)
);

CREATE TABLE IF NOT EXISTS payments (
  id BIGINT PRIMARY KEY AUTO_INCREMENT,
  order_id BIGINT NOT NULL,
  amount_bdt DECIMAL(12,2) NOT NULL,
  status ENUM('PENDING','PAID','FAILED') NOT NULL DEFAULT 'PENDING',
  method VARCHAR(50) NOT NULL DEFAULT 'DUMMY',
  transaction_ref VARCHAR(100),
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  FOREIGN KEY (order_id) REFERENCES orders(id)
);

-- USED ITEMS MARKETPLACE
CREATE TABLE IF NOT EXISTS condition_levels (
  id BIGINT PRIMARY KEY AUTO_INCREMENT,
  label VARCHAR(50) NOT NULL UNIQUE
);

CREATE TABLE IF NOT EXISTS used_listings (
  id BIGINT PRIMARY KEY AUTO_INCREMENT,
  seller_id BIGINT NOT NULL,
  category_id BIGINT NOT NULL,
  condition_id BIGINT NOT NULL,
  title VARCHAR(255) NOT NULL,
  description TEXT,
  price_bdt DECIMAL(12,2) NOT NULL,
  warranty_flag ENUM('YES','NO') NOT NULL DEFAULT 'NO',
  status ENUM('ACTIVE','SOLD','REMOVED') NOT NULL DEFAULT 'ACTIVE',
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  FOREIGN KEY (seller_id) REFERENCES users(id),
  FOREIGN KEY (category_id) REFERENCES categories(id),
  FOREIGN KEY (condition_id) REFERENCES condition_levels(id)
);

CREATE TABLE IF NOT EXISTS used_images (
  id BIGINT PRIMARY KEY AUTO_INCREMENT,
  listing_id BIGINT NOT NULL,
  image_url VARCHAR(500) NOT NULL,
  sort_order INT NOT NULL DEFAULT 0,
  FOREIGN KEY (listing_id) REFERENCES used_listings(id)
);

CREATE TABLE IF NOT EXISTS used_videos (
  id BIGINT PRIMARY KEY AUTO_INCREMENT,
  listing_id BIGINT NOT NULL,
  video_url VARCHAR(500) NOT NULL,
  FOREIGN KEY (listing_id) REFERENCES used_listings(id)
);

CREATE TABLE IF NOT EXISTS used_item_history (
  id BIGINT PRIMARY KEY AUTO_INCREMENT,
  listing_id BIGINT NOT NULL,
  owner_count INT NOT NULL DEFAULT 1,
  usage_duration_months INT,
  FOREIGN KEY (listing_id) REFERENCES used_listings(id)
);

CREATE TABLE IF NOT EXISTS used_item_repairs (
  id BIGINT PRIMARY KEY AUTO_INCREMENT,
  listing_id BIGINT NOT NULL,
  details TEXT NOT NULL,
  repaired_at DATE,
  FOREIGN KEY (listing_id) REFERENCES used_listings(id)
);

-- REPAIR SERVICES
CREATE TABLE IF NOT EXISTS technicians (
  id BIGINT PRIMARY KEY AUTO_INCREMENT,
  user_id BIGINT NOT NULL UNIQUE,
  specialization ENUM('Electronics','Electrical','Furniture','Appliances') NOT NULL,
  pickup_available BOOLEAN NOT NULL DEFAULT FALSE,
  level ENUM('Beginner','Verified','Expert') NOT NULL DEFAULT 'Beginner',
  rating_avg DECIMAL(3,2) NOT NULL DEFAULT 0.00,
  completion_rate DECIMAL(5,2) NOT NULL DEFAULT 0.00,
  FOREIGN KEY (user_id) REFERENCES users(id)
);

CREATE TABLE IF NOT EXISTS technician_skills (
  id BIGINT PRIMARY KEY AUTO_INCREMENT,
  technician_id BIGINT NOT NULL,
  skill VARCHAR(120) NOT NULL,
  FOREIGN KEY (technician_id) REFERENCES technicians(id)
);

CREATE TABLE IF NOT EXISTS service_listings (
  id BIGINT PRIMARY KEY AUTO_INCREMENT,
  technician_id BIGINT NOT NULL,
  category VARCHAR(120) NOT NULL,
  price_min_bdt DECIMAL(12,2) NOT NULL,
  price_max_bdt DECIMAL(12,2) NOT NULL,
  availability_note VARCHAR(255),
  status ENUM('ACTIVE','INACTIVE') NOT NULL DEFAULT 'ACTIVE',
  FOREIGN KEY (technician_id) REFERENCES technicians(id)
);

CREATE TABLE IF NOT EXISTS repair_requests (
  id BIGINT PRIMARY KEY AUTO_INCREMENT,
  customer_id BIGINT NOT NULL,
  category VARCHAR(120) NOT NULL,
  description TEXT NOT NULL,
  pickup_needed BOOLEAN NOT NULL DEFAULT FALSE,
  status ENUM('OPEN','QUOTED','BOOKED','COMPLETED','CANCELLED') NOT NULL DEFAULT 'OPEN',
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  FOREIGN KEY (customer_id) REFERENCES users(id)
);

CREATE TABLE IF NOT EXISTS repair_media (
  id BIGINT PRIMARY KEY AUTO_INCREMENT,
  request_id BIGINT NOT NULL,
  media_url VARCHAR(500) NOT NULL,
  media_type ENUM('IMAGE','VIDEO') NOT NULL,
  FOREIGN KEY (request_id) REFERENCES repair_requests(id)
);

CREATE TABLE IF NOT EXISTS repair_quotes (
  id BIGINT PRIMARY KEY AUTO_INCREMENT,
  request_id BIGINT NOT NULL,
  technician_id BIGINT NOT NULL,
  quote_bdt DECIMAL(12,2) NOT NULL,
  plan TEXT,
  status ENUM('SENT','ACCEPTED','REJECTED') NOT NULL DEFAULT 'SENT',
  FOREIGN KEY (request_id) REFERENCES repair_requests(id),
  FOREIGN KEY (technician_id) REFERENCES technicians(id)
);

CREATE TABLE IF NOT EXISTS repair_bookings (
  id BIGINT PRIMARY KEY AUTO_INCREMENT,
  request_id BIGINT NOT NULL,
  technician_id BIGINT NOT NULL,
  scheduled_date DATE NOT NULL,
  status ENUM('CONFIRMED','REJECTED','COMPLETED','CANCELLED') NOT NULL DEFAULT 'CONFIRMED',
  FOREIGN KEY (request_id) REFERENCES repair_requests(id),
  FOREIGN KEY (technician_id) REFERENCES technicians(id)
);

CREATE TABLE IF NOT EXISTS service_completion (
  id BIGINT PRIMARY KEY AUTO_INCREMENT,
  booking_id BIGINT NOT NULL,
  completed_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  notes TEXT,
  FOREIGN KEY (booking_id) REFERENCES repair_bookings(id)
);

-- AUCTIONS
CREATE TABLE IF NOT EXISTS auctions (
  id BIGINT PRIMARY KEY AUTO_INCREMENT,
  vendor_id BIGINT NOT NULL,
  title VARCHAR(255) NOT NULL,
  type ENUM('STANDARD','FLASH','REVERSE','RESERVE') NOT NULL,
  status ENUM('CREATED','APPROVED','PREPARING','ACTIVE','EXTENDED','CLOSED','COMPLETED') NOT NULL DEFAULT 'CREATED',
  start_time DATETIME NOT NULL,
  end_time DATETIME NOT NULL,
  reserve_price_bdt DECIMAL(12,2),
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  FOREIGN KEY (vendor_id) REFERENCES users(id)
);

CREATE TABLE IF NOT EXISTS auction_lots (
  id BIGINT PRIMARY KEY AUTO_INCREMENT,
  auction_id BIGINT NOT NULL,
  title VARCHAR(255) NOT NULL,
  description TEXT,
  starting_price_bdt DECIMAL(12,2) NOT NULL,
  current_bid_bdt DECIMAL(12,2) NOT NULL DEFAULT 0.00,
  status ENUM('PREPARING','ACTIVE','CLOSED') NOT NULL DEFAULT 'PREPARING',
  FOREIGN KEY (auction_id) REFERENCES auctions(id)
);

CREATE TABLE IF NOT EXISTS auction_images (
  id BIGINT PRIMARY KEY AUTO_INCREMENT,
  lot_id BIGINT NOT NULL,
  image_url VARCHAR(500) NOT NULL,
  FOREIGN KEY (lot_id) REFERENCES auction_lots(id)
);

CREATE TABLE IF NOT EXISTS bids (
  id BIGINT PRIMARY KEY AUTO_INCREMENT,
  lot_id BIGINT NOT NULL,
  bidder_id BIGINT NOT NULL,
  amount_bdt DECIMAL(12,2) NOT NULL,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  FOREIGN KEY (lot_id) REFERENCES auction_lots(id),
  FOREIGN KEY (bidder_id) REFERENCES users(id)
);

CREATE TABLE IF NOT EXISTS watchlist (
  id BIGINT PRIMARY KEY AUTO_INCREMENT,
  user_id BIGINT NOT NULL,
  lot_id BIGINT NOT NULL,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  UNIQUE (user_id, lot_id),
  FOREIGN KEY (user_id) REFERENCES users(id),
  FOREIGN KEY (lot_id) REFERENCES auction_lots(id)
);

CREATE TABLE IF NOT EXISTS auction_approvals (
  id BIGINT PRIMARY KEY AUTO_INCREMENT,
  auction_id BIGINT NOT NULL,
  admin_id BIGINT NOT NULL,
  status ENUM('APPROVED','REJECTED') NOT NULL,
  notes TEXT,
  decided_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  FOREIGN KEY (auction_id) REFERENCES auctions(id),
  FOREIGN KEY (admin_id) REFERENCES users(id)
);

CREATE TABLE IF NOT EXISTS auction_status_log (
  id BIGINT PRIMARY KEY AUTO_INCREMENT,
  auction_id BIGINT NOT NULL,
  old_status VARCHAR(30) NOT NULL,
  new_status VARCHAR(30) NOT NULL,
  changed_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  FOREIGN KEY (auction_id) REFERENCES auctions(id)
);

-- TRUST, FRAUD, REPORTS, REPUTATION
CREATE TABLE IF NOT EXISTS trust_scores (
  user_id BIGINT PRIMARY KEY,
  score DECIMAL(5,2) NOT NULL DEFAULT 50.00,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  FOREIGN KEY (user_id) REFERENCES users(id)
);

CREATE TABLE IF NOT EXISTS trust_events (
  id BIGINT PRIMARY KEY AUTO_INCREMENT,
  user_id BIGINT NOT NULL,
  event_type VARCHAR(100) NOT NULL,
  delta DECIMAL(5,2) NOT NULL,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  FOREIGN KEY (user_id) REFERENCES users(id)
);

CREATE TABLE IF NOT EXISTS fraud_flags (
  id BIGINT PRIMARY KEY AUTO_INCREMENT,
  user_id BIGINT NOT NULL,
  reason VARCHAR(255) NOT NULL,
  status ENUM('OPEN','REVIEWED','RESOLVED') NOT NULL DEFAULT 'OPEN',
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  FOREIGN KEY (user_id) REFERENCES users(id)
);

CREATE TABLE IF NOT EXISTS fraud_events (
  id BIGINT PRIMARY KEY AUTO_INCREMENT,
  user_id BIGINT NOT NULL,
  event_type VARCHAR(100) NOT NULL,
  details TEXT,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  FOREIGN KEY (user_id) REFERENCES users(id)
);

CREATE TABLE IF NOT EXISTS reports (
  id BIGINT PRIMARY KEY AUTO_INCREMENT,
  reporter_id BIGINT NOT NULL,
  reported_id BIGINT NOT NULL,
  reason TEXT NOT NULL,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  FOREIGN KEY (reporter_id) REFERENCES users(id),
  FOREIGN KEY (reported_id) REFERENCES users(id)
);

CREATE TABLE IF NOT EXISTS bidder_reputation (
  user_id BIGINT PRIMARY KEY,
  win_rate DECIMAL(5,2) NOT NULL DEFAULT 0.00,
  payment_success_rate DECIMAL(5,2) NOT NULL DEFAULT 0.00,
  cancellation_rate DECIMAL(5,2) NOT NULL DEFAULT 0.00,
  FOREIGN KEY (user_id) REFERENCES users(id)
);

CREATE TABLE IF NOT EXISTS bidder_restrictions (
  id BIGINT PRIMARY KEY AUTO_INCREMENT,
  vendor_id BIGINT NOT NULL,
  bidder_id BIGINT NOT NULL,
  reason VARCHAR(255),
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  UNIQUE (vendor_id, bidder_id),
  FOREIGN KEY (vendor_id) REFERENCES users(id),
  FOREIGN KEY (bidder_id) REFERENCES users(id)
);

-- CHAT & NOTIFICATIONS
CREATE TABLE IF NOT EXISTS conversations (
  id BIGINT PRIMARY KEY AUTO_INCREMENT,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS conversation_members (
  conversation_id BIGINT NOT NULL,
  user_id BIGINT NOT NULL,
  PRIMARY KEY (conversation_id, user_id),
  FOREIGN KEY (conversation_id) REFERENCES conversations(id),
  FOREIGN KEY (user_id) REFERENCES users(id)
);

CREATE TABLE IF NOT EXISTS messages (
  id BIGINT PRIMARY KEY AUTO_INCREMENT,
  conversation_id BIGINT NOT NULL,
  sender_id BIGINT NOT NULL,
  message TEXT NOT NULL,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  FOREIGN KEY (conversation_id) REFERENCES conversations(id),
  FOREIGN KEY (sender_id) REFERENCES users(id)
);

CREATE TABLE IF NOT EXISTS notifications (
  id BIGINT PRIMARY KEY AUTO_INCREMENT,
  user_id BIGINT NOT NULL,
  title VARCHAR(120) NOT NULL,
  body TEXT NOT NULL,
  is_read BOOLEAN NOT NULL DEFAULT FALSE,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  FOREIGN KEY (user_id) REFERENCES users(id)
);

CREATE TABLE IF NOT EXISTS notification_subscriptions (
  id BIGINT PRIMARY KEY AUTO_INCREMENT,
  user_id BIGINT NOT NULL,
  category VARCHAR(120) NOT NULL,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  FOREIGN KEY (user_id) REFERENCES users(id)
);
