-- =========================================================
-- ATOMDROPS DATABASE SCHEMA — PostgreSQL (Supabase)
-- Smart Multi-Vendor Marketplace
-- =========================================================

-- Trigger function for updated_at columns
CREATE OR REPLACE FUNCTION update_updated_at_column()
RETURNS TRIGGER AS $$
BEGIN
    NEW.updated_at = NOW();
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

-- =========================================================
-- CORE: USERS & ROLES
-- =========================================================

CREATE TABLE IF NOT EXISTS roles (
    id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    name VARCHAR(50) NOT NULL UNIQUE
);

CREATE TABLE IF NOT EXISTS users (
    id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    email VARCHAR(191) NOT NULL UNIQUE,
    password_hash VARCHAR(255) NOT NULL,
    display_name VARCHAR(120) NOT NULL,
    phone VARCHAR(30),
    status VARCHAR(20) NOT NULL DEFAULT 'ACTIVE' CHECK (status IN ('ACTIVE','SUSPENDED','BANNED')),
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP
);

CREATE TRIGGER update_users_updated_at
    BEFORE UPDATE ON users
    FOR EACH ROW
    EXECUTE FUNCTION update_updated_at_column();

CREATE TABLE IF NOT EXISTS user_roles (
    user_id BIGINT NOT NULL,
    role_id BIGINT NOT NULL,
    PRIMARY KEY (user_id, role_id),
    FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE,
    FOREIGN KEY (role_id) REFERENCES roles(id) ON DELETE CASCADE
);

-- =========================================================
-- MARKETPLACE: CATEGORIES, PRODUCTS, INVENTORY
-- =========================================================

CREATE TABLE IF NOT EXISTS categories (
    id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    name VARCHAR(120) NOT NULL UNIQUE,
    parent_id BIGINT,
    updated_at TIMESTAMP,
    FOREIGN KEY (parent_id) REFERENCES categories(id) ON DELETE SET NULL
);

CREATE TRIGGER update_categories_updated_at
    BEFORE UPDATE ON categories
    FOR EACH ROW
    EXECUTE FUNCTION update_updated_at_column();

CREATE TABLE IF NOT EXISTS products (
    id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    vendor_id BIGINT NOT NULL,
    category_id BIGINT NOT NULL,
    name VARCHAR(255) NOT NULL,
    description TEXT,
    price_bdt DECIMAL(12,2) NOT NULL,
    status VARCHAR(20) NOT NULL DEFAULT 'ACTIVE' CHECK (status IN ('DRAFT','ACTIVE','INACTIVE','OUT_OF_STOCK')),
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP,
    FOREIGN KEY (vendor_id) REFERENCES users(id) ON DELETE RESTRICT,
    FOREIGN KEY (category_id) REFERENCES categories(id) ON DELETE RESTRICT
);
CREATE INDEX idx_products_vendor_status ON products(vendor_id, status);
CREATE INDEX idx_products_category_status ON products(category_id, status);

CREATE TRIGGER update_products_updated_at
    BEFORE UPDATE ON products
    FOR EACH ROW
    EXECUTE FUNCTION update_updated_at_column();

CREATE TABLE IF NOT EXISTS product_images (
    id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    product_id BIGINT NOT NULL,
    image_url VARCHAR(500) NOT NULL,
    sort_order INT NOT NULL DEFAULT 0,
    FOREIGN KEY (product_id) REFERENCES products(id) ON DELETE CASCADE
);
CREATE INDEX idx_product_images_product ON product_images(product_id, sort_order);

CREATE TABLE IF NOT EXISTS inventory (
    id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    product_id BIGINT NOT NULL UNIQUE,
    stock_qty INT NOT NULL DEFAULT 0,
    low_stock_threshold INT NOT NULL DEFAULT 5,
    updated_at TIMESTAMP,
    FOREIGN KEY (product_id) REFERENCES products(id) ON DELETE CASCADE
);

CREATE TRIGGER update_inventory_updated_at
    BEFORE UPDATE ON inventory
    FOR EACH ROW
    EXECUTE FUNCTION update_updated_at_column();

-- =========================================================
-- ORDERS & PAYMENTS
-- =========================================================

CREATE TABLE IF NOT EXISTS orders (
    id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    customer_id BIGINT NOT NULL,
    total_bdt DECIMAL(12,2) NOT NULL,
    status VARCHAR(20) NOT NULL DEFAULT 'PLACED' CHECK (status IN ('PLACED','PAID','SHIPPED','DELIVERED','CANCELLED')),
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP,
    FOREIGN KEY (customer_id) REFERENCES users(id) ON DELETE RESTRICT
);
CREATE INDEX idx_orders_customer_status ON orders(customer_id, status);
CREATE INDEX idx_orders_created_at ON orders(created_at);

CREATE TRIGGER update_orders_updated_at
    BEFORE UPDATE ON orders
    FOR EACH ROW
    EXECUTE FUNCTION update_updated_at_column();

CREATE TABLE IF NOT EXISTS order_items (
    id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    order_id BIGINT NOT NULL,
    product_id BIGINT NOT NULL,
    qty INT NOT NULL,
    unit_price_bdt DECIMAL(12,2) NOT NULL,
    FOREIGN KEY (order_id) REFERENCES orders(id) ON DELETE CASCADE,
    FOREIGN KEY (product_id) REFERENCES products(id) ON DELETE RESTRICT
);
CREATE INDEX idx_order_items_order ON order_items(order_id);

CREATE TABLE IF NOT EXISTS payments (
    id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    order_id BIGINT NOT NULL,
    amount_bdt DECIMAL(12,2) NOT NULL,
    status VARCHAR(20) NOT NULL DEFAULT 'PENDING' CHECK (status IN ('PENDING','PAID','FAILED')),
    method VARCHAR(50) NOT NULL DEFAULT 'DUMMY',
    transaction_ref VARCHAR(100),
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP,
    FOREIGN KEY (order_id) REFERENCES orders(id) ON DELETE CASCADE
);
CREATE INDEX idx_payments_order ON payments(order_id);

CREATE TRIGGER update_payments_updated_at
    BEFORE UPDATE ON payments
    FOR EACH ROW
    EXECUTE FUNCTION update_updated_at_column();

-- =========================================================
-- USED ITEMS MARKETPLACE
-- =========================================================

CREATE TABLE IF NOT EXISTS condition_levels (
    id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    label VARCHAR(50) NOT NULL UNIQUE
);

CREATE TABLE IF NOT EXISTS used_listings (
    id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    seller_id BIGINT NOT NULL,
    category_id BIGINT NOT NULL,
    condition_id BIGINT NOT NULL,
    title VARCHAR(255) NOT NULL,
    description TEXT,
    price_bdt DECIMAL(12,2) NOT NULL,
    warranty_flag VARCHAR(3) NOT NULL DEFAULT 'NO' CHECK (warranty_flag IN ('YES','NO')),
    status VARCHAR(20) NOT NULL DEFAULT 'ACTIVE' CHECK (status IN ('ACTIVE','SOLD','REMOVED')),
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP,
    FOREIGN KEY (seller_id) REFERENCES users(id) ON DELETE RESTRICT,
    FOREIGN KEY (category_id) REFERENCES categories(id) ON DELETE RESTRICT,
    FOREIGN KEY (condition_id) REFERENCES condition_levels(id) ON DELETE RESTRICT
);
CREATE INDEX idx_used_listings_seller_status ON used_listings(seller_id, status);
CREATE INDEX idx_used_listings_category_status ON used_listings(category_id, status);

CREATE TRIGGER update_used_listings_updated_at
    BEFORE UPDATE ON used_listings
    FOR EACH ROW
    EXECUTE FUNCTION update_updated_at_column();

CREATE TABLE IF NOT EXISTS used_images (
    id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    listing_id BIGINT NOT NULL,
    image_url VARCHAR(500) NOT NULL,
    sort_order INT NOT NULL DEFAULT 0,
    FOREIGN KEY (listing_id) REFERENCES used_listings(id) ON DELETE CASCADE
);
CREATE INDEX idx_used_images_listing ON used_images(listing_id, sort_order);

CREATE TABLE IF NOT EXISTS used_videos (
    id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    listing_id BIGINT NOT NULL,
    video_url VARCHAR(500) NOT NULL,
    FOREIGN KEY (listing_id) REFERENCES used_listings(id) ON DELETE CASCADE
);
CREATE INDEX idx_used_videos_listing ON used_videos(listing_id);

CREATE TABLE IF NOT EXISTS used_item_history (
    id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    listing_id BIGINT NOT NULL,
    owner_count INT NOT NULL DEFAULT 1,
    usage_duration_months INT,
    FOREIGN KEY (listing_id) REFERENCES used_listings(id) ON DELETE CASCADE
);
CREATE INDEX idx_used_item_history_listing ON used_item_history(listing_id);

CREATE TABLE IF NOT EXISTS used_item_repairs (
    id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    listing_id BIGINT NOT NULL,
    details TEXT NOT NULL,
    repaired_at DATE,
    FOREIGN KEY (listing_id) REFERENCES used_listings(id) ON DELETE CASCADE
);
CREATE INDEX idx_used_item_repairs_listing ON used_item_repairs(listing_id);

-- =========================================================
-- REPAIR SERVICES
-- =========================================================

CREATE TABLE IF NOT EXISTS technicians (
    id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    user_id BIGINT NOT NULL UNIQUE,
    specialization VARCHAR(30) NOT NULL CHECK (specialization IN ('Electronics','Electrical','Furniture','Appliances')),
    pickup_available BOOLEAN NOT NULL DEFAULT FALSE,
    level VARCHAR(20) NOT NULL DEFAULT 'Beginner' CHECK (level IN ('Beginner','Verified','Expert')),
    rating_avg DECIMAL(3,2) NOT NULL DEFAULT 0.00,
    completion_rate DECIMAL(5,2) NOT NULL DEFAULT 0.00,
    updated_at TIMESTAMP,
    FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE
);

CREATE TRIGGER update_technicians_updated_at
    BEFORE UPDATE ON technicians
    FOR EACH ROW
    EXECUTE FUNCTION update_updated_at_column();

CREATE TABLE IF NOT EXISTS technician_skills (
    id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    technician_id BIGINT NOT NULL,
    skill VARCHAR(120) NOT NULL,
    updated_at TIMESTAMP,
    FOREIGN KEY (technician_id) REFERENCES technicians(id) ON DELETE CASCADE
);

CREATE TRIGGER update_technician_skills_updated_at
    BEFORE UPDATE ON technician_skills
    FOR EACH ROW
    EXECUTE FUNCTION update_updated_at_column();

CREATE TABLE IF NOT EXISTS service_listings (
    id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    technician_id BIGINT NOT NULL,
    category VARCHAR(120) NOT NULL,
    price_min_bdt DECIMAL(12,2) NOT NULL,
    price_max_bdt DECIMAL(12,2) NOT NULL,
    availability_note VARCHAR(255),
    status VARCHAR(20) NOT NULL DEFAULT 'ACTIVE' CHECK (status IN ('ACTIVE','INACTIVE')),
    updated_at TIMESTAMP,
    FOREIGN KEY (technician_id) REFERENCES technicians(id) ON DELETE CASCADE
);

CREATE TRIGGER update_service_listings_updated_at
    BEFORE UPDATE ON service_listings
    FOR EACH ROW
    EXECUTE FUNCTION update_updated_at_column();

CREATE TABLE IF NOT EXISTS repair_requests (
    id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    customer_id BIGINT NOT NULL,
    category VARCHAR(120) NOT NULL,
    description TEXT NOT NULL,
    pickup_needed BOOLEAN NOT NULL DEFAULT FALSE,
    status VARCHAR(20) NOT NULL DEFAULT 'OPEN' CHECK (status IN ('OPEN','QUOTED','BOOKED','COMPLETED','CANCELLED')),
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP,
    FOREIGN KEY (customer_id) REFERENCES users(id) ON DELETE RESTRICT
);

CREATE TRIGGER update_repair_requests_updated_at
    BEFORE UPDATE ON repair_requests
    FOR EACH ROW
    EXECUTE FUNCTION update_updated_at_column();

CREATE TABLE IF NOT EXISTS repair_media (
    id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    request_id BIGINT NOT NULL,
    media_url VARCHAR(500) NOT NULL,
    media_type VARCHAR(10) NOT NULL CHECK (media_type IN ('IMAGE','VIDEO')),
    updated_at TIMESTAMP,
    FOREIGN KEY (request_id) REFERENCES repair_requests(id) ON DELETE CASCADE
);

CREATE TRIGGER update_repair_media_updated_at
    BEFORE UPDATE ON repair_media
    FOR EACH ROW
    EXECUTE FUNCTION update_updated_at_column();

CREATE TABLE IF NOT EXISTS repair_quotes (
    id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    request_id BIGINT NOT NULL,
    technician_id BIGINT NOT NULL,
    quote_bdt DECIMAL(12,2) NOT NULL,
    plan TEXT,
    status VARCHAR(20) NOT NULL DEFAULT 'SENT' CHECK (status IN ('SENT','ACCEPTED','REJECTED')),
    updated_at TIMESTAMP,
    FOREIGN KEY (request_id) REFERENCES repair_requests(id) ON DELETE CASCADE,
    FOREIGN KEY (technician_id) REFERENCES technicians(id) ON DELETE CASCADE
);

CREATE TRIGGER update_repair_quotes_updated_at
    BEFORE UPDATE ON repair_quotes
    FOR EACH ROW
    EXECUTE FUNCTION update_updated_at_column();

CREATE TABLE IF NOT EXISTS repair_bookings (
    id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    request_id BIGINT NOT NULL,
    technician_id BIGINT NOT NULL,
    scheduled_date DATE NOT NULL,
    status VARCHAR(20) NOT NULL DEFAULT 'CONFIRMED' CHECK (status IN ('CONFIRMED','REJECTED','COMPLETED','CANCELLED')),
    updated_at TIMESTAMP,
    FOREIGN KEY (request_id) REFERENCES repair_requests(id) ON DELETE CASCADE,
    FOREIGN KEY (technician_id) REFERENCES technicians(id) ON DELETE CASCADE
);

CREATE TRIGGER update_repair_bookings_updated_at
    BEFORE UPDATE ON repair_bookings
    FOR EACH ROW
    EXECUTE FUNCTION update_updated_at_column();

CREATE TABLE IF NOT EXISTS service_completion (
    id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    booking_id BIGINT NOT NULL,
    completed_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    notes TEXT,
    updated_at TIMESTAMP,
    FOREIGN KEY (booking_id) REFERENCES repair_bookings(id) ON DELETE CASCADE
);

CREATE TRIGGER update_service_completion_updated_at
    BEFORE UPDATE ON service_completion
    FOR EACH ROW
    EXECUTE FUNCTION update_updated_at_column();

-- =========================================================
-- AUCTIONS
-- =========================================================

CREATE TABLE IF NOT EXISTS auctions (
    id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    vendor_id BIGINT NOT NULL,
    title VARCHAR(255) NOT NULL,
    type VARCHAR(20) NOT NULL CHECK (type IN ('STANDARD','FLASH','REVERSE','RESERVE')),
    status VARCHAR(20) NOT NULL DEFAULT 'CREATED' CHECK (status IN ('CREATED','APPROVED','PREPARING','ACTIVE','EXTENDED','CLOSED','COMPLETED')),
    start_time TIMESTAMP NOT NULL,
    end_time TIMESTAMP NOT NULL,
    reserve_price_bdt DECIMAL(12,2),
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP,
    FOREIGN KEY (vendor_id) REFERENCES users(id) ON DELETE RESTRICT
);

CREATE TRIGGER update_auctions_updated_at
    BEFORE UPDATE ON auctions
    FOR EACH ROW
    EXECUTE FUNCTION update_updated_at_column();

CREATE TABLE IF NOT EXISTS auction_lots (
    id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    auction_id BIGINT NOT NULL,
    title VARCHAR(255) NOT NULL,
    description TEXT,
    starting_price_bdt DECIMAL(12,2) NOT NULL,
    current_bid_bdt DECIMAL(12,2) NOT NULL DEFAULT 0.00,
    status VARCHAR(20) NOT NULL DEFAULT 'PREPARING' CHECK (status IN ('PREPARING','ACTIVE','CLOSED')),
    updated_at TIMESTAMP,
    FOREIGN KEY (auction_id) REFERENCES auctions(id) ON DELETE CASCADE
);
CREATE INDEX idx_auction_lots_auction ON auction_lots(auction_id);

CREATE TRIGGER update_auction_lots_updated_at
    BEFORE UPDATE ON auction_lots
    FOR EACH ROW
    EXECUTE FUNCTION update_updated_at_column();

CREATE TABLE IF NOT EXISTS auction_images (
    id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    lot_id BIGINT NOT NULL,
    image_url VARCHAR(500) NOT NULL,
    FOREIGN KEY (lot_id) REFERENCES auction_lots(id) ON DELETE CASCADE
);
CREATE INDEX idx_auction_images_lot ON auction_images(lot_id);

CREATE TABLE IF NOT EXISTS bids (
    id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    lot_id BIGINT NOT NULL,
    bidder_id BIGINT NOT NULL,
    amount_bdt DECIMAL(12,2) NOT NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP,
    FOREIGN KEY (lot_id) REFERENCES auction_lots(id) ON DELETE CASCADE,
    FOREIGN KEY (bidder_id) REFERENCES users(id) ON DELETE RESTRICT
);
CREATE INDEX idx_bids_lot_amount ON bids(lot_id, amount_bdt DESC);
CREATE INDEX idx_bids_bidder_lot ON bids(bidder_id, lot_id);

CREATE TRIGGER update_bids_updated_at
    BEFORE UPDATE ON bids
    FOR EACH ROW
    EXECUTE FUNCTION update_updated_at_column();

CREATE TABLE IF NOT EXISTS watchlist (
    id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    user_id BIGINT NOT NULL,
    lot_id BIGINT NOT NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    UNIQUE (user_id, lot_id),
    FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE,
    FOREIGN KEY (lot_id) REFERENCES auction_lots(id) ON DELETE CASCADE
);
CREATE INDEX idx_watchlist_user ON watchlist(user_id);

CREATE TABLE IF NOT EXISTS auction_approvals (
    id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    auction_id BIGINT NOT NULL,
    admin_id BIGINT NOT NULL,
    status VARCHAR(20) NOT NULL CHECK (status IN ('APPROVED','REJECTED')),
    notes TEXT,
    decided_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (auction_id) REFERENCES auctions(id) ON DELETE CASCADE,
    FOREIGN KEY (admin_id) REFERENCES users(id) ON DELETE RESTRICT
);
CREATE INDEX idx_auction_approvals_auction ON auction_approvals(auction_id);

CREATE TABLE IF NOT EXISTS auction_status_log (
    id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    auction_id BIGINT NOT NULL,
    old_status VARCHAR(30) NOT NULL,
    new_status VARCHAR(30) NOT NULL,
    changed_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (auction_id) REFERENCES auctions(id) ON DELETE CASCADE
);
CREATE INDEX idx_auction_status_log_auction ON auction_status_log(auction_id);

-- =========================================================
-- TRUST, FRAUD, REPORTS, REPUTATION
-- =========================================================

CREATE TABLE IF NOT EXISTS trust_scores (
    user_id BIGINT PRIMARY KEY,
    score DECIMAL(5,2) NOT NULL DEFAULT 50.00,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE
);

CREATE TRIGGER update_trust_scores_updated_at
    BEFORE UPDATE ON trust_scores
    FOR EACH ROW
    EXECUTE FUNCTION update_updated_at_column();

CREATE TABLE IF NOT EXISTS trust_events (
    id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    user_id BIGINT NOT NULL,
    event_type VARCHAR(100) NOT NULL,
    delta DECIMAL(5,2) NOT NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE
);
CREATE INDEX idx_trust_events_user ON trust_events(user_id);

CREATE TABLE IF NOT EXISTS fraud_flags (
    id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    user_id BIGINT NOT NULL,
    reason VARCHAR(255) NOT NULL,
    status VARCHAR(20) NOT NULL DEFAULT 'OPEN' CHECK (status IN ('OPEN','REVIEWED','RESOLVED')),
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP,
    FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE
);
CREATE INDEX idx_fraud_flags_user_status ON fraud_flags(user_id, status);

CREATE TRIGGER update_fraud_flags_updated_at
    BEFORE UPDATE ON fraud_flags
    FOR EACH ROW
    EXECUTE FUNCTION update_updated_at_column();

CREATE TABLE IF NOT EXISTS fraud_events (
    id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    user_id BIGINT NOT NULL,
    event_type VARCHAR(100) NOT NULL,
    details TEXT,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP,
    FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE
);

CREATE TRIGGER update_fraud_events_updated_at
    BEFORE UPDATE ON fraud_events
    FOR EACH ROW
    EXECUTE FUNCTION update_updated_at_column();

CREATE TABLE IF NOT EXISTS reports (
    id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    reporter_id BIGINT NOT NULL,
    reported_id BIGINT NOT NULL,
    reason TEXT NOT NULL,
    status VARCHAR(20) NOT NULL DEFAULT 'OPEN' CHECK (status IN ('OPEN','REVIEWED','RESOLVED')),
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    resolved_at TIMESTAMP,
    updated_at TIMESTAMP,
    FOREIGN KEY (reporter_id) REFERENCES users(id) ON DELETE RESTRICT,
    FOREIGN KEY (reported_id) REFERENCES users(id) ON DELETE RESTRICT
);
CREATE INDEX idx_reports_reported ON reports(reported_id);
CREATE INDEX idx_reports_reporter ON reports(reporter_id);

CREATE TRIGGER update_reports_updated_at
    BEFORE UPDATE ON reports
    FOR EACH ROW
    EXECUTE FUNCTION update_updated_at_column();

CREATE TABLE IF NOT EXISTS bidder_reputation (
    user_id BIGINT PRIMARY KEY,
    win_rate DECIMAL(5,2) NOT NULL DEFAULT 0.00,
    payment_success_rate DECIMAL(5,2) NOT NULL DEFAULT 0.00,
    cancellation_rate DECIMAL(5,2) NOT NULL DEFAULT 0.00,
    updated_at TIMESTAMP,
    FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE
);

CREATE TRIGGER update_bidder_reputation_updated_at
    BEFORE UPDATE ON bidder_reputation
    FOR EACH ROW
    EXECUTE FUNCTION update_updated_at_column();

CREATE TABLE IF NOT EXISTS bidder_restrictions (
    id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    vendor_id BIGINT NOT NULL,
    bidder_id BIGINT NOT NULL,
    reason VARCHAR(255),
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    UNIQUE (vendor_id, bidder_id),
    FOREIGN KEY (vendor_id) REFERENCES users(id) ON DELETE CASCADE,
    FOREIGN KEY (bidder_id) REFERENCES users(id) ON DELETE CASCADE
);
CREATE INDEX idx_bidder_restrictions_vendor ON bidder_restrictions(vendor_id);

-- =========================================================
-- CHAT & NOTIFICATIONS
-- =========================================================

CREATE TABLE IF NOT EXISTS conversations (
    id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS conversation_members (
    conversation_id BIGINT NOT NULL,
    user_id BIGINT NOT NULL,
    PRIMARY KEY (conversation_id, user_id),
    FOREIGN KEY (conversation_id) REFERENCES conversations(id) ON DELETE CASCADE,
    FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE
);
CREATE INDEX idx_conversation_members_user ON conversation_members(user_id);

CREATE TABLE IF NOT EXISTS messages (
    id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    conversation_id BIGINT NOT NULL,
    sender_id BIGINT NOT NULL,
    message TEXT NOT NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (conversation_id) REFERENCES conversations(id) ON DELETE CASCADE,
    FOREIGN KEY (sender_id) REFERENCES users(id) ON DELETE RESTRICT
);
CREATE INDEX idx_messages_conversation ON messages(conversation_id, created_at);

CREATE TABLE IF NOT EXISTS notifications (
    id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    user_id BIGINT NOT NULL,
    title VARCHAR(120) NOT NULL,
    body TEXT NOT NULL,
    is_read BOOLEAN NOT NULL DEFAULT FALSE,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP,
    FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE
);
CREATE INDEX idx_notifications_user_read ON notifications(user_id, is_read, created_at);

CREATE TRIGGER update_notifications_updated_at
    BEFORE UPDATE ON notifications
    FOR EACH ROW
    EXECUTE FUNCTION update_updated_at_column();

CREATE TABLE IF NOT EXISTS notification_subscriptions (
    id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    user_id BIGINT NOT NULL,
    category VARCHAR(120) NOT NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE
);
CREATE INDEX idx_notification_subscriptions_user ON notification_subscriptions(user_id);

-- =========================================================
-- REVIEWS
-- =========================================================

CREATE TABLE IF NOT EXISTS reviews (
    id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    reviewer_id BIGINT NOT NULL,
    reviewee_id BIGINT NOT NULL,
    product_id BIGINT,
    rating INT NOT NULL CHECK (rating >= 1 AND rating <= 5),
    comment TEXT,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (reviewer_id) REFERENCES users(id) ON DELETE CASCADE,
    FOREIGN KEY (reviewee_id) REFERENCES users(id) ON DELETE CASCADE,
    FOREIGN KEY (product_id) REFERENCES products(id) ON DELETE SET NULL
);
CREATE INDEX idx_reviews_reviewee ON reviews(reviewee_id);
CREATE INDEX idx_reviews_product ON reviews(product_id);
CREATE INDEX idx_reviews_reviewer ON reviews(reviewer_id);

-- =========================================================
-- RETURNS
-- =========================================================

CREATE TABLE IF NOT EXISTS returns (
    id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    order_item_id BIGINT NOT NULL,
    customer_id BIGINT NOT NULL,
    reason TEXT NOT NULL,
    status VARCHAR(20) NOT NULL DEFAULT 'OPEN' CHECK (status IN ('OPEN','APPROVED','REJECTED','COMPLETED')),
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    resolved_at TIMESTAMP,
    FOREIGN KEY (order_item_id) REFERENCES order_items(id) ON DELETE CASCADE,
    FOREIGN KEY (customer_id) REFERENCES users(id) ON DELETE RESTRICT
);
CREATE INDEX idx_returns_customer ON returns(customer_id);
CREATE INDEX idx_returns_order_item ON returns(order_item_id);

-- =========================================================
-- USER AGREEMENTS
-- =========================================================

CREATE TABLE IF NOT EXISTS user_agreements (
    id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    user_id BIGINT NOT NULL,
    agreement_type VARCHAR(50) NOT NULL CHECK (agreement_type IN ('TERMS','PRIVACY','AUCTION_RULES')),
    accepted_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    ip_address VARCHAR(45),
    FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE
);
CREATE INDEX idx_user_agreements_user ON user_agreements(user_id);

-- =========================================================
-- PASSWORD RESET TOKENS
-- =========================================================

CREATE TABLE IF NOT EXISTS password_reset_tokens (
    id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    user_id BIGINT NOT NULL,
    token VARCHAR(255) NOT NULL UNIQUE,
    expires_at TIMESTAMP NOT NULL,
    used BOOLEAN NOT NULL DEFAULT FALSE,
    FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE
);
CREATE INDEX idx_password_reset_tokens_token ON password_reset_tokens(token);

-- =========================================================
-- FULLTEXT SEARCH SUPPORT (PostgreSQL GIN indexes)
-- =========================================================

ALTER TABLE products ADD COLUMN IF NOT EXISTS search_vector tsvector
    GENERATED ALWAYS AS (to_tsvector('english', COALESCE(name, '') || ' ' || COALESCE(description, ''))) STORED;
CREATE INDEX IF NOT EXISTS idx_products_search ON products USING GIN(search_vector);

ALTER TABLE used_listings ADD COLUMN IF NOT EXISTS search_vector tsvector
    GENERATED ALWAYS AS (to_tsvector('english', COALESCE(title, '') || ' ' || COALESCE(description, ''))) STORED;
CREATE INDEX IF NOT EXISTS idx_used_listings_search ON used_listings USING GIN(search_vector);
