-- ============================================================
-- ATOMDROPS DATABASE SCHEMA v5.0
-- PostgreSQL (Supabase) | 71 Tables
-- Reordered so no forward FK references occur
-- ============================================================

-- Wipe existing schema
DROP SCHEMA IF EXISTS public CASCADE;
CREATE SCHEMA public;
GRANT ALL ON SCHEMA public TO postgres;
GRANT ALL ON SCHEMA public TO public;

-- ── SECTION 0: UTILITY ───────────────────────────────────────
CREATE OR REPLACE FUNCTION fn_set_updated_at()
RETURNS TRIGGER AS $$
BEGIN NEW.updated_at = NOW(); RETURN NEW; END;
$$ LANGUAGE plpgsql;

-- ── SECTION 1: ROLES ─────────────────────────────────────────
CREATE TABLE IF NOT EXISTS roles (
    id   BIGINT      PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    name VARCHAR(50) NOT NULL UNIQUE
);

-- ── SECTION 2: USERS & AUTH ──────────────────────────────────
CREATE TABLE IF NOT EXISTS users (
    id            BIGINT       PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    email         VARCHAR(191) NOT NULL UNIQUE,
    password_hash VARCHAR(255) NOT NULL,
    display_name  VARCHAR(120) NOT NULL,
    phone         VARCHAR(30),
    avatar_url    TEXT,
    status        VARCHAR(20)  NOT NULL DEFAULT 'ACTIVE'
                      CHECK (status IN ('ACTIVE','SUSPENDED','BANNED')),
    deleted_at    TIMESTAMP,
    created_at    TIMESTAMP    NOT NULL DEFAULT NOW(),
    updated_at    TIMESTAMP    NOT NULL DEFAULT NOW()
);
CREATE INDEX IF NOT EXISTS idx_users_email      ON users(email);
CREATE INDEX IF NOT EXISTS idx_users_status     ON users(status)     WHERE deleted_at IS NULL;
CREATE INDEX IF NOT EXISTS idx_users_deleted_at ON users(deleted_at) WHERE deleted_at IS NOT NULL;
CREATE TRIGGER trg_users_updated_at
    BEFORE UPDATE ON users FOR EACH ROW EXECUTE FUNCTION fn_set_updated_at();

CREATE TABLE IF NOT EXISTS user_roles (
    user_id BIGINT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    role_id BIGINT NOT NULL REFERENCES roles(id) ON DELETE CASCADE,
    PRIMARY KEY (user_id, role_id)
);

CREATE TABLE IF NOT EXISTS user_badges (
    id         BIGINT      PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    user_id    BIGINT      NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    badge_type VARCHAR(50) NOT NULL
                   CHECK (badge_type IN ('VERIFIED_SELLER','TOP_RESELLER',
                                         'EXPERT_TECHNICIAN','TRUSTED_BIDDER')),
    awarded_at TIMESTAMP   NOT NULL DEFAULT NOW(),
    expires_at TIMESTAMP,
    is_active  BOOLEAN     NOT NULL DEFAULT TRUE,
    UNIQUE (user_id, badge_type)
);
CREATE INDEX IF NOT EXISTS idx_user_badges_user ON user_badges(user_id) WHERE is_active = TRUE;

CREATE TABLE IF NOT EXISTS ban_history (
    id         BIGINT      PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    user_id    BIGINT      NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    action     VARCHAR(20) NOT NULL
                   CHECK (action IN ('BANNED','SUSPENDED','UNBANNED','REINSTATED')),
    reason     TEXT        NOT NULL,
    admin_id   BIGINT      REFERENCES users(id) ON DELETE SET NULL,
    expires_at TIMESTAMP,
    created_at TIMESTAMP   NOT NULL DEFAULT NOW()
);
CREATE INDEX IF NOT EXISTS idx_ban_history_user ON ban_history(user_id, created_at DESC);

CREATE TABLE IF NOT EXISTS customer_profiles (
    id            BIGINT  PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    user_id       BIGINT  NOT NULL UNIQUE REFERENCES users(id) ON DELETE CASCADE,
    bio           TEXT,
    location      VARCHAR(120),
    website_url   TEXT,
    date_of_birth DATE,
    gender        VARCHAR(20) CHECK (gender IN ('MALE','FEMALE','OTHER','PREFER_NOT_TO_SAY')),
    created_at    TIMESTAMP NOT NULL DEFAULT NOW(),
    updated_at    TIMESTAMP NOT NULL DEFAULT NOW()
);
CREATE TRIGGER trg_customer_profiles_updated_at
    BEFORE UPDATE ON customer_profiles FOR EACH ROW EXECUTE FUNCTION fn_set_updated_at();

CREATE TABLE IF NOT EXISTS addresses (
    id           BIGINT       PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    user_id      BIGINT       NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    label        VARCHAR(60)  NOT NULL DEFAULT 'Home',
    full_name    VARCHAR(120) NOT NULL,
    phone        VARCHAR(30)  NOT NULL,
    address_line TEXT         NOT NULL,
    city         VARCHAR(100) NOT NULL,
    area         VARCHAR(100),
    postal_code  VARCHAR(20),
    is_default   BOOLEAN      NOT NULL DEFAULT FALSE,
    created_at   TIMESTAMP    NOT NULL DEFAULT NOW(),
    updated_at   TIMESTAMP    NOT NULL DEFAULT NOW()
);
CREATE INDEX IF NOT EXISTS idx_addresses_user ON addresses(user_id);
CREATE TRIGGER trg_addresses_updated_at
    BEFORE UPDATE ON addresses FOR EACH ROW EXECUTE FUNCTION fn_set_updated_at();

CREATE TABLE IF NOT EXISTS password_reset_tokens (
    id         BIGINT       PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    user_id    BIGINT       NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    token      VARCHAR(255) NOT NULL UNIQUE,
    expires_at TIMESTAMP    NOT NULL,
    used       BOOLEAN      NOT NULL DEFAULT FALSE,
    created_at TIMESTAMP    NOT NULL DEFAULT NOW()
);
CREATE INDEX IF NOT EXISTS idx_prt_token ON password_reset_tokens(token);

CREATE TABLE IF NOT EXISTS user_agreements (
    id             BIGINT      PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    user_id        BIGINT      NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    agreement_type VARCHAR(50) NOT NULL
                       CHECK (agreement_type IN ('TERMS','PRIVACY','AUCTION_RULES')),
    accepted_at    TIMESTAMP   NOT NULL DEFAULT NOW(),
    ip_address     VARCHAR(45),
    UNIQUE (user_id, agreement_type)
);
CREATE INDEX IF NOT EXISTS idx_user_agreements_user ON user_agreements(user_id);

-- ── SECTION 3: AUDIT LOGS ────────────────────────────────────
CREATE TABLE IF NOT EXISTS audit_logs (
    id          BIGINT      PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    actor_id    BIGINT      REFERENCES users(id) ON DELETE SET NULL,
    action      VARCHAR(60) NOT NULL,
    entity_type VARCHAR(60) NOT NULL,
    entity_id   BIGINT,
    old_data    JSONB,
    new_data    JSONB,
    ip_address  VARCHAR(45),
    created_at  TIMESTAMP   NOT NULL DEFAULT NOW()
);
CREATE INDEX IF NOT EXISTS idx_audit_logs_actor      ON audit_logs(actor_id);
CREATE INDEX IF NOT EXISTS idx_audit_logs_entity     ON audit_logs(entity_type, entity_id);
CREATE INDEX IF NOT EXISTS idx_audit_logs_created_at ON audit_logs(created_at DESC);
-- Removed: partial index with NOW() not allowed (non-IMMUTABLE)

-- ── SECTION 3.5: ROLE UPGRADES & PAYMENTS ────────────────────
CREATE TABLE IF NOT EXISTS role_upgrades (
    id           BIGINT      PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    user_id      BIGINT      NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    role         VARCHAR(20) NOT NULL
                   CHECK (role IN ('VENDOR','TECHNICIAN')),
    amount_bdt   DECIMAL(12,2) NOT NULL DEFAULT 99.00,
    status       VARCHAR(20) NOT NULL DEFAULT 'PENDING_PAYMENT'
                   CHECK (status IN ('PENDING_PAYMENT','PAID','ACTIVE','FAILED','CANCELLED')),
    activated_at TIMESTAMP,
    created_at   TIMESTAMP   NOT NULL DEFAULT NOW(),
    updated_at   TIMESTAMP   NOT NULL DEFAULT NOW(),
    UNIQUE (user_id, role)
);
CREATE INDEX IF NOT EXISTS idx_role_upgrades_user ON role_upgrades(user_id, status);
CREATE TRIGGER trg_role_upgrades_updated_at
    BEFORE UPDATE ON role_upgrades FOR EACH ROW EXECUTE FUNCTION fn_set_updated_at();

CREATE TABLE IF NOT EXISTS upgrade_payments (
    id           BIGINT       PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    upgrade_id   BIGINT       NOT NULL REFERENCES role_upgrades(id) ON DELETE CASCADE,
    user_id      BIGINT       NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    amount_bdt   DECIMAL(12,2) NOT NULL,
    currency     VARCHAR(10)  NOT NULL DEFAULT 'BDT',
    method       VARCHAR(20)  NOT NULL
                   CHECK (method IN ('BKASH','NAGAD','CARD')),
    status       VARCHAR(20)  NOT NULL DEFAULT 'INITIATED'
                   CHECK (status IN ('INITIATED','SUCCESS','FAILED')),
    provider_ref VARCHAR(100),
    created_at   TIMESTAMP    NOT NULL DEFAULT NOW(),
    updated_at   TIMESTAMP    NOT NULL DEFAULT NOW()
);
CREATE INDEX IF NOT EXISTS idx_upgrade_payments_user ON upgrade_payments(user_id, created_at DESC);
CREATE INDEX IF NOT EXISTS idx_upgrade_payments_upgrade ON upgrade_payments(upgrade_id, created_at DESC);
CREATE TRIGGER trg_upgrade_payments_updated_at
    BEFORE UPDATE ON upgrade_payments FOR EACH ROW EXECUTE FUNCTION fn_set_updated_at();

-- ── SECTION 4: PLATFORM SETTINGS ─────────────────────────────
CREATE TABLE IF NOT EXISTS platform_settings (
    key         VARCHAR(100) PRIMARY KEY,
    value       TEXT         NOT NULL,
    data_type   VARCHAR(20)  NOT NULL DEFAULT 'STRING'
                    CHECK (data_type IN ('STRING','INTEGER','DECIMAL','BOOLEAN','JSON')),
    description TEXT,
    updated_by  BIGINT       REFERENCES users(id) ON DELETE SET NULL,
    created_at  TIMESTAMP    NOT NULL DEFAULT NOW(),
    updated_at  TIMESTAMP    NOT NULL DEFAULT NOW()
);
CREATE TRIGGER trg_platform_settings_updated_at
    BEFORE UPDATE ON platform_settings FOR EACH ROW EXECUTE FUNCTION fn_set_updated_at();

-- ── SECTION 5: ANALYTICS SNAPSHOTS ───────────────────────────
CREATE TABLE IF NOT EXISTS analytics_snapshots (
    id                    BIGINT        PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    snapshot_date         DATE          NOT NULL UNIQUE,
    new_users_count       INT           NOT NULL DEFAULT 0,
    active_users_count    INT           NOT NULL DEFAULT 0,
    new_orders_count      INT           NOT NULL DEFAULT 0,
    gross_revenue_bdt     DECIMAL(14,2) NOT NULL DEFAULT 0.00,
    platform_fees_bdt     DECIMAL(14,2) NOT NULL DEFAULT 0.00,
    new_used_listings     INT           NOT NULL DEFAULT 0,
    new_repair_requests   INT           NOT NULL DEFAULT 0,
    completed_repairs     INT           NOT NULL DEFAULT 0,
    new_auctions_count    INT           NOT NULL DEFAULT 0,
    auction_revenue_bdt   DECIMAL(14,2) NOT NULL DEFAULT 0.00,
    fraud_flags_raised    INT           NOT NULL DEFAULT 0,
    fraud_flags_resolved  INT           NOT NULL DEFAULT 0,
    new_reports_count     INT           NOT NULL DEFAULT 0,
    created_at            TIMESTAMP     NOT NULL DEFAULT NOW()
);
CREATE INDEX IF NOT EXISTS idx_analytics_date ON analytics_snapshots(snapshot_date DESC);

-- ── SECTION 6: SYSTEM NOTIFICATIONS ──────────────────────────
CREATE TABLE IF NOT EXISTS system_notifications (
    id           BIGINT       PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    title        VARCHAR(200) NOT NULL,
    body         TEXT         NOT NULL,
    type         VARCHAR(30)  NOT NULL DEFAULT 'INFO'
                     CHECK (type IN ('INFO','WARNING','MAINTENANCE','POLICY_UPDATE')),
    target_roles VARCHAR(100),
    is_active    BOOLEAN      NOT NULL DEFAULT TRUE,
    starts_at    TIMESTAMP    NOT NULL DEFAULT NOW(),
    ends_at      TIMESTAMP,
    created_by   BIGINT       REFERENCES users(id) ON DELETE SET NULL,
    created_at   TIMESTAMP    NOT NULL DEFAULT NOW(),
    updated_at   TIMESTAMP    NOT NULL DEFAULT NOW()
);
CREATE INDEX IF NOT EXISTS idx_system_notifs_active ON system_notifications(is_active, starts_at)
    WHERE is_active = TRUE;
CREATE TRIGGER trg_system_notifications_updated_at
    BEFORE UPDATE ON system_notifications FOR EACH ROW EXECUTE FUNCTION fn_set_updated_at();

-- ── SECTION 7: VENDOR PROFILES ───────────────────────────────
CREATE TABLE IF NOT EXISTS vendor_profiles (
    id                  BIGINT       PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    user_id             BIGINT       NOT NULL UNIQUE REFERENCES users(id) ON DELETE CASCADE,
    shop_name           VARCHAR(180) NOT NULL,
    shop_slug           VARCHAR(180) NOT NULL UNIQUE,
    logo_url            TEXT,
    banner_url          TEXT,
    bio                 TEXT,
    location            VARCHAR(120),
    website_url         TEXT,
    social_links        JSONB,
    verification_status VARCHAR(20)  NOT NULL DEFAULT 'PENDING'
                            CHECK (verification_status IN ('PENDING','VERIFIED','REJECTED')),
    response_rate       DECIMAL(5,2) NOT NULL DEFAULT 0.00,
    created_at          TIMESTAMP    NOT NULL DEFAULT NOW(),
    updated_at          TIMESTAMP    NOT NULL DEFAULT NOW()
);
CREATE INDEX IF NOT EXISTS idx_vendor_profiles_slug ON vendor_profiles(shop_slug);
CREATE TRIGGER trg_vendor_profiles_updated_at
    BEFORE UPDATE ON vendor_profiles FOR EACH ROW EXECUTE FUNCTION fn_set_updated_at();

-- ── SECTION 8: CATEGORIES ────────────────────────────────────
CREATE TABLE IF NOT EXISTS categories (
    id         BIGINT       PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    name       VARCHAR(120) NOT NULL,
    slug       VARCHAR(120) NOT NULL UNIQUE,
    parent_id  BIGINT       REFERENCES categories(id) ON DELETE SET NULL,
    icon_url   TEXT,
    sort_order INT          NOT NULL DEFAULT 0,
    created_at TIMESTAMP    NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMP    NOT NULL DEFAULT NOW(),
    UNIQUE (name, parent_id)
);
CREATE INDEX IF NOT EXISTS idx_categories_parent ON categories(parent_id);
CREATE TRIGGER trg_categories_updated_at
    BEFORE UPDATE ON categories FOR EACH ROW EXECUTE FUNCTION fn_set_updated_at();

-- ── SECTION 13 (MOVED UP): USED ITEMS MARKETPLACE ────────────
CREATE TABLE IF NOT EXISTS condition_levels (
    id         BIGINT      PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    label      VARCHAR(50) NOT NULL UNIQUE,
    sort_order INT         NOT NULL DEFAULT 0,
    created_at TIMESTAMP   NOT NULL DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS used_listings (
    id             BIGINT        PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    seller_id      BIGINT        NOT NULL REFERENCES users(id)            ON DELETE RESTRICT,
    category_id    BIGINT        NOT NULL REFERENCES categories(id)       ON DELETE RESTRICT,
    condition_id   BIGINT        NOT NULL REFERENCES condition_levels(id) ON DELETE RESTRICT,
    title          VARCHAR(255)  NOT NULL,
    description    TEXT,
    price_bdt      DECIMAL(12,2) NOT NULL CHECK (price_bdt >= 0),
    warranty_flag  VARCHAR(3)    NOT NULL DEFAULT 'NO' CHECK (warranty_flag IN ('YES','NO')),
    offers_enabled BOOLEAN       NOT NULL DEFAULT FALSE,
    status         VARCHAR(20)   NOT NULL DEFAULT 'ACTIVE'
                       CHECK (status IN ('ACTIVE','SOLD','REMOVED')),
    deleted_at     TIMESTAMP,
    created_at     TIMESTAMP     NOT NULL DEFAULT NOW(),
    updated_at     TIMESTAMP     NOT NULL DEFAULT NOW()
);
CREATE INDEX IF NOT EXISTS idx_used_listings_seller_status   ON used_listings(seller_id, status)
    WHERE deleted_at IS NULL;
CREATE INDEX IF NOT EXISTS idx_used_listings_category_status ON used_listings(category_id, status)
    WHERE deleted_at IS NULL;
CREATE INDEX IF NOT EXISTS idx_used_listings_price           ON used_listings(price_bdt)
    WHERE deleted_at IS NULL;
CREATE TRIGGER trg_used_listings_updated_at
    BEFORE UPDATE ON used_listings FOR EACH ROW EXECUTE FUNCTION fn_set_updated_at();

ALTER TABLE used_listings ADD COLUMN IF NOT EXISTS search_vector tsvector
    GENERATED ALWAYS AS (
        to_tsvector('english', COALESCE(title,'') || ' ' || COALESCE(description,''))
    ) STORED;
CREATE INDEX IF NOT EXISTS idx_used_listings_search ON used_listings USING GIN(search_vector);

CREATE TABLE IF NOT EXISTS used_images (
    id         BIGINT    PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    listing_id BIGINT    NOT NULL REFERENCES used_listings(id) ON DELETE CASCADE,
    image_url  TEXT      NOT NULL,
    sort_order INT       NOT NULL DEFAULT 0,
    created_at TIMESTAMP NOT NULL DEFAULT NOW()
);
CREATE INDEX IF NOT EXISTS idx_used_images_listing ON used_images(listing_id, sort_order);

CREATE TABLE IF NOT EXISTS used_videos (
    id         BIGINT    PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    listing_id BIGINT    NOT NULL REFERENCES used_listings(id) ON DELETE CASCADE,
    video_url  TEXT      NOT NULL,
    created_at TIMESTAMP NOT NULL DEFAULT NOW()
);
CREATE INDEX IF NOT EXISTS idx_used_videos_listing ON used_videos(listing_id);

CREATE TABLE IF NOT EXISTS used_item_history (
    id                    BIGINT    PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    listing_id            BIGINT    NOT NULL UNIQUE REFERENCES used_listings(id) ON DELETE CASCADE,
    owner_count           INT       NOT NULL DEFAULT 1 CHECK (owner_count >= 1),
    usage_duration_months INT                CHECK (usage_duration_months >= 0),
    created_at            TIMESTAMP NOT NULL DEFAULT NOW(),
    updated_at            TIMESTAMP NOT NULL DEFAULT NOW()
);
CREATE TRIGGER trg_used_item_history_updated_at
    BEFORE UPDATE ON used_item_history FOR EACH ROW EXECUTE FUNCTION fn_set_updated_at();

CREATE TABLE IF NOT EXISTS used_item_repairs (
    id          BIGINT    PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    listing_id  BIGINT    NOT NULL REFERENCES used_listings(id) ON DELETE CASCADE,
    details     TEXT      NOT NULL,
    repaired_at DATE,
    created_at  TIMESTAMP NOT NULL DEFAULT NOW()
);
CREATE INDEX IF NOT EXISTS idx_used_item_repairs_listing ON used_item_repairs(listing_id);

CREATE TABLE IF NOT EXISTS used_listing_offers (
    id         BIGINT        PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    listing_id BIGINT        NOT NULL REFERENCES used_listings(id) ON DELETE CASCADE,
    buyer_id   BIGINT        NOT NULL REFERENCES users(id)         ON DELETE CASCADE,
    offer_bdt  DECIMAL(12,2) NOT NULL CHECK (offer_bdt > 0),
    status     VARCHAR(20)   NOT NULL DEFAULT 'PENDING'
                   CHECK (status IN ('PENDING','ACCEPTED','REJECTED','EXPIRED','WITHDRAWN')),
    expires_at TIMESTAMP     NOT NULL,
    created_at TIMESTAMP     NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMP     NOT NULL DEFAULT NOW(),
    UNIQUE (listing_id, buyer_id)
);
CREATE INDEX IF NOT EXISTS idx_used_listing_offers_listing ON used_listing_offers(listing_id, status);
CREATE INDEX IF NOT EXISTS idx_used_listing_offers_buyer   ON used_listing_offers(buyer_id);
CREATE TRIGGER trg_used_listing_offers_updated_at
    BEFORE UPDATE ON used_listing_offers FOR EACH ROW EXECUTE FUNCTION fn_set_updated_at();

CREATE TABLE IF NOT EXISTS used_listing_offer_messages (
    id                BIGINT        PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    offer_id          BIGINT        NOT NULL REFERENCES used_listing_offers(id) ON DELETE CASCADE,
    sender_id         BIGINT        NOT NULL REFERENCES users(id) ON DELETE RESTRICT,
    message           TEXT,
    counter_offer_bdt DECIMAL(12,2),
    created_at        TIMESTAMP     NOT NULL DEFAULT NOW()
);
CREATE INDEX IF NOT EXISTS idx_offer_messages_offer ON used_listing_offer_messages(offer_id, created_at);

-- ── SECTION 9: PRODUCTS ──────────────────────────────────────
CREATE TABLE IF NOT EXISTS products (
    id            BIGINT        PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    vendor_id     BIGINT        NOT NULL REFERENCES users(id)      ON DELETE RESTRICT,
    category_id   BIGINT        NOT NULL REFERENCES categories(id) ON DELETE RESTRICT,
    name          VARCHAR(255)  NOT NULL,
    description   TEXT,
    price_bdt     DECIMAL(12,2) NOT NULL CHECK (price_bdt >= 0),
    status        VARCHAR(20)   NOT NULL DEFAULT 'DRAFT'
                    CHECK (status IN ('DRAFT','ACTIVE','INACTIVE','OUT_OF_STOCK')),
    shipping_type VARCHAR(10)   NOT NULL DEFAULT 'FREE',
    deleted_at    TIMESTAMP,
    created_at    TIMESTAMP     NOT NULL DEFAULT NOW(),
    updated_at    TIMESTAMP     NOT NULL DEFAULT NOW()
);
CREATE INDEX IF NOT EXISTS idx_products_vendor_status   ON products(vendor_id, status)
    WHERE deleted_at IS NULL;
CREATE INDEX IF NOT EXISTS idx_products_category_status ON products(category_id, status)
    WHERE deleted_at IS NULL;
CREATE INDEX IF NOT EXISTS idx_products_price           ON products(price_bdt)
    WHERE deleted_at IS NULL;
CREATE TRIGGER trg_products_updated_at
    BEFORE UPDATE ON products FOR EACH ROW EXECUTE FUNCTION fn_set_updated_at();

ALTER TABLE products ADD COLUMN IF NOT EXISTS search_vector tsvector
    GENERATED ALWAYS AS (
        to_tsvector('english', COALESCE(name,'') || ' ' || COALESCE(description,''))
    ) STORED;
CREATE INDEX IF NOT EXISTS idx_products_search ON products USING GIN(search_vector);

CREATE TABLE IF NOT EXISTS product_images (
    id         BIGINT    PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    product_id BIGINT    NOT NULL REFERENCES products(id) ON DELETE CASCADE,
    image_url  TEXT      NOT NULL,
    sort_order INT       NOT NULL DEFAULT 0,
    created_at TIMESTAMP NOT NULL DEFAULT NOW()
);
CREATE INDEX IF NOT EXISTS idx_product_images_product ON product_images(product_id, sort_order);

CREATE TABLE IF NOT EXISTS product_variants (
    id               BIGINT        PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    product_id       BIGINT        NOT NULL REFERENCES products(id) ON DELETE CASCADE,
    variant_label    VARCHAR(255)  NOT NULL,
    sku              VARCHAR(100)  UNIQUE,
    price_offset_bdt DECIMAL(12,2) NOT NULL DEFAULT 0.00,
    created_at       TIMESTAMP     NOT NULL DEFAULT NOW(),
    updated_at       TIMESTAMP     NOT NULL DEFAULT NOW()
);
CREATE INDEX IF NOT EXISTS idx_product_variants_product ON product_variants(product_id);
CREATE TRIGGER trg_product_variants_updated_at
    BEFORE UPDATE ON product_variants FOR EACH ROW EXECUTE FUNCTION fn_set_updated_at();

CREATE TABLE IF NOT EXISTS inventory (
    id                 BIGINT    PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    product_id         BIGINT    NOT NULL REFERENCES products(id)         ON DELETE CASCADE,
    product_variant_id BIGINT             REFERENCES product_variants(id) ON DELETE CASCADE,
    stock_qty          INT       NOT NULL DEFAULT 0 CHECK (stock_qty >= 0),
    low_stock_threshold INT      NOT NULL DEFAULT 5,
    updated_at         TIMESTAMP NOT NULL DEFAULT NOW(),
    UNIQUE (product_id, product_variant_id)
);
CREATE TRIGGER trg_inventory_updated_at
    BEFORE UPDATE ON inventory FOR EACH ROW EXECUTE FUNCTION fn_set_updated_at();

CREATE TABLE IF NOT EXISTS product_questions (
    id          BIGINT    PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    product_id  BIGINT    NOT NULL REFERENCES products(id) ON DELETE CASCADE,
    asker_id    BIGINT    NOT NULL REFERENCES users(id)    ON DELETE CASCADE,
    question    TEXT      NOT NULL,
    answer      TEXT,
    answered_by BIGINT    REFERENCES users(id) ON DELETE SET NULL,
    answered_at TIMESTAMP,
    is_public   BOOLEAN   NOT NULL DEFAULT TRUE,
    created_at  TIMESTAMP NOT NULL DEFAULT NOW(),
    updated_at  TIMESTAMP NOT NULL DEFAULT NOW()
);
CREATE INDEX IF NOT EXISTS idx_product_questions_product ON product_questions(product_id, is_public);
CREATE TRIGGER trg_product_questions_updated_at
    BEFORE UPDATE ON product_questions FOR EACH ROW EXECUTE FUNCTION fn_set_updated_at();

-- ── SECTION 10: CART & COUPONS ───────────────────────────────
CREATE TABLE IF NOT EXISTS carts (
    id         BIGINT      PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    user_id    BIGINT      NOT NULL UNIQUE REFERENCES users(id) ON DELETE CASCADE,
    status     VARCHAR(20) NOT NULL DEFAULT 'ACTIVE',
    expires_at TIMESTAMP,
    created_at TIMESTAMP   NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMP   NOT NULL DEFAULT NOW()
);
CREATE TRIGGER trg_carts_updated_at
    BEFORE UPDATE ON carts FOR EACH ROW EXECUTE FUNCTION fn_set_updated_at();

CREATE TABLE IF NOT EXISTS cart_items (
    id                 BIGINT      PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    cart_id            BIGINT      NOT NULL REFERENCES carts(id)             ON DELETE CASCADE,
    item_type          VARCHAR(20) NOT NULL DEFAULT 'PRODUCT'
                           CHECK (item_type IN ('PRODUCT','USED_ITEM')),
    product_id         BIGINT               REFERENCES products(id)           ON DELETE CASCADE,
    product_variant_id BIGINT               REFERENCES product_variants(id)   ON DELETE SET NULL,
    used_listing_id    BIGINT               REFERENCES used_listings(id)      ON DELETE CASCADE,
    qty                INT         NOT NULL DEFAULT 1 CHECK (qty > 0),
    created_at         TIMESTAMP   NOT NULL DEFAULT NOW(),
    updated_at         TIMESTAMP   NOT NULL DEFAULT NOW(),
    CHECK (
        (item_type = 'PRODUCT'   AND product_id IS NOT NULL AND used_listing_id IS NULL) OR
        (item_type = 'USED_ITEM' AND used_listing_id IS NOT NULL AND product_id IS NULL)
    ),
    UNIQUE (cart_id, product_id, product_variant_id),
    UNIQUE (cart_id, used_listing_id)
);
CREATE INDEX IF NOT EXISTS idx_cart_items_cart ON cart_items(cart_id);
CREATE TRIGGER trg_cart_items_updated_at
    BEFORE UPDATE ON cart_items FOR EACH ROW EXECUTE FUNCTION fn_set_updated_at();

CREATE TABLE IF NOT EXISTS coupons (
    id               BIGINT        PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    code             VARCHAR(50)   NOT NULL UNIQUE,
    description      TEXT,
    discount_type    VARCHAR(20)   NOT NULL CHECK (discount_type IN ('FLAT','PERCENT')),
    discount_value   DECIMAL(12,2) NOT NULL CHECK (discount_value > 0),
    min_order_bdt    DECIMAL(12,2) NOT NULL DEFAULT 0.00,
    max_discount_bdt DECIMAL(12,2),
    max_uses         INT,
    uses_count       INT           NOT NULL DEFAULT 0,
    valid_from       TIMESTAMP     NOT NULL DEFAULT NOW(),
    valid_until      TIMESTAMP,
    is_active        BOOLEAN       NOT NULL DEFAULT TRUE,
    created_by       BIGINT        REFERENCES users(id) ON DELETE SET NULL,
    created_at       TIMESTAMP     NOT NULL DEFAULT NOW(),
    updated_at       TIMESTAMP     NOT NULL DEFAULT NOW()
);
CREATE INDEX IF NOT EXISTS idx_coupons_code ON coupons(code) WHERE is_active = TRUE;
CREATE TRIGGER trg_coupons_updated_at
    BEFORE UPDATE ON coupons FOR EACH ROW EXECUTE FUNCTION fn_set_updated_at();

-- ── SECTION 11: ORDERS, PAYMENTS & SHIPMENTS ─────────────────
CREATE TABLE IF NOT EXISTS orders (
    id                        BIGINT        PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    customer_id               BIGINT        NOT NULL REFERENCES users(id)    ON DELETE RESTRICT,
    shipping_address_id       BIGINT                 REFERENCES addresses(id) ON DELETE SET NULL,
    shipping_address_snapshot JSONB,
    coupon_id                 BIGINT                 REFERENCES coupons(id)   ON DELETE SET NULL,
    subtotal_bdt              DECIMAL(12,2) NOT NULL CHECK (subtotal_bdt >= 0),
    shipping_fee_bdt          DECIMAL(12,2) NOT NULL DEFAULT 0.00,
    discount_bdt              DECIMAL(12,2) NOT NULL DEFAULT 0.00,
    tax_bdt                   DECIMAL(12,2) NOT NULL DEFAULT 0.00,
    total_bdt                 DECIMAL(12,2) NOT NULL CHECK (total_bdt >= 0),
    status                    VARCHAR(20)   NOT NULL DEFAULT 'PLACED'
                                  CHECK (status IN ('PLACED','PAID','PROCESSING',
                                                    'SHIPPED','DELIVERED','CANCELLED','RETURNED')),
    note                      TEXT,
    created_at                TIMESTAMP     NOT NULL DEFAULT NOW(),
    updated_at                TIMESTAMP     NOT NULL DEFAULT NOW()
);
CREATE INDEX IF NOT EXISTS idx_orders_customer_status ON orders(customer_id, status);
CREATE INDEX IF NOT EXISTS idx_orders_created_at      ON orders(created_at DESC);
CREATE TRIGGER trg_orders_updated_at
    BEFORE UPDATE ON orders FOR EACH ROW EXECUTE FUNCTION fn_set_updated_at();

CREATE TABLE IF NOT EXISTS order_status_log (
    id         BIGINT      PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    order_id   BIGINT      NOT NULL REFERENCES orders(id) ON DELETE CASCADE,
    old_status VARCHAR(30) NOT NULL,
    new_status VARCHAR(30) NOT NULL,
    changed_by BIGINT               REFERENCES users(id) ON DELETE SET NULL,
    note       TEXT,
    changed_at TIMESTAMP   NOT NULL DEFAULT NOW()
);
CREATE INDEX IF NOT EXISTS idx_order_status_log_order ON order_status_log(order_id, changed_at DESC);

CREATE TABLE IF NOT EXISTS coupon_uses (
    id        BIGINT    PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    coupon_id BIGINT    NOT NULL REFERENCES coupons(id) ON DELETE RESTRICT,
    user_id   BIGINT    NOT NULL REFERENCES users(id)   ON DELETE RESTRICT,
    order_id  BIGINT    NOT NULL REFERENCES orders(id)  ON DELETE CASCADE,
    used_at   TIMESTAMP NOT NULL DEFAULT NOW(),
    UNIQUE (coupon_id, user_id)
);
CREATE INDEX IF NOT EXISTS idx_coupon_uses_coupon ON coupon_uses(coupon_id);
CREATE INDEX IF NOT EXISTS idx_coupon_uses_user   ON coupon_uses(user_id);

CREATE TABLE IF NOT EXISTS order_items (
    id                 BIGINT        PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    order_id           BIGINT        NOT NULL REFERENCES orders(id)           ON DELETE CASCADE,
    item_type          VARCHAR(20)   NOT NULL DEFAULT 'PRODUCT'
                           CHECK (item_type IN ('PRODUCT','USED_ITEM')),
    product_id         BIGINT                 REFERENCES products(id)          ON DELETE RESTRICT,
    used_listing_id    BIGINT                 REFERENCES used_listings(id)     ON DELETE RESTRICT,
    product_variant_id BIGINT                 REFERENCES product_variants(id)  ON DELETE SET NULL,
    variant_label      VARCHAR(255),
    qty                INT           NOT NULL CHECK (qty > 0),
    unit_price_bdt     DECIMAL(12,2) NOT NULL CHECK (unit_price_bdt >= 0),
    created_at         TIMESTAMP     NOT NULL DEFAULT NOW(),
    CHECK (
        (item_type = 'PRODUCT'   AND product_id IS NOT NULL AND used_listing_id IS NULL) OR
        (item_type = 'USED_ITEM' AND used_listing_id IS NOT NULL AND product_id IS NULL)
    )
);
CREATE INDEX IF NOT EXISTS idx_order_items_order        ON order_items(order_id);
CREATE INDEX IF NOT EXISTS idx_order_items_product      ON order_items(product_id);
CREATE INDEX IF NOT EXISTS idx_order_items_used_listing ON order_items(used_listing_id);

CREATE TABLE IF NOT EXISTS payments (
    id               BIGINT        PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    order_id         BIGINT        NOT NULL REFERENCES orders(id) ON DELETE CASCADE,
    amount_bdt       DECIMAL(12,2) NOT NULL CHECK (amount_bdt > 0),
    status           VARCHAR(20)   NOT NULL DEFAULT 'PENDING'
                         CHECK (status IN ('PENDING','PAID','FAILED','REFUNDED')),
    method           VARCHAR(50)   NOT NULL DEFAULT 'DUMMY',
    gateway_name     VARCHAR(50),
    transaction_ref  VARCHAR(100)  UNIQUE,
    gateway_response JSONB,
    paid_at          TIMESTAMP,
    created_at       TIMESTAMP     NOT NULL DEFAULT NOW(),
    updated_at       TIMESTAMP     NOT NULL DEFAULT NOW()
);
CREATE INDEX IF NOT EXISTS idx_payments_order       ON payments(order_id);
CREATE INDEX IF NOT EXISTS idx_payments_status      ON payments(status);
CREATE INDEX IF NOT EXISTS idx_payments_transaction ON payments(transaction_ref);
CREATE TRIGGER trg_payments_updated_at
    BEFORE UPDATE ON payments FOR EACH ROW EXECUTE FUNCTION fn_set_updated_at();

CREATE TABLE IF NOT EXISTS vendor_commissions (
    id              BIGINT        PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    order_item_id   BIGINT        NOT NULL UNIQUE REFERENCES order_items(id) ON DELETE CASCADE,
    vendor_id       BIGINT        NOT NULL REFERENCES users(id)              ON DELETE RESTRICT,
    sale_amount_bdt DECIMAL(12,2) NOT NULL,
    commission_rate DECIMAL(5,2)  NOT NULL,
    commission_bdt  DECIMAL(12,2) NOT NULL,
    net_payout_bdt  DECIMAL(12,2) NOT NULL,
    status          VARCHAR(20)   NOT NULL DEFAULT 'PENDING'
                        CHECK (status IN ('PENDING','PAID','HELD','CANCELLED')),
    created_at      TIMESTAMP     NOT NULL DEFAULT NOW(),
    updated_at      TIMESTAMP     NOT NULL DEFAULT NOW()
);
CREATE INDEX IF NOT EXISTS idx_vendor_commissions_vendor ON vendor_commissions(vendor_id, status);
CREATE TRIGGER trg_vendor_commissions_updated_at
    BEFORE UPDATE ON vendor_commissions FOR EACH ROW EXECUTE FUNCTION fn_set_updated_at();

CREATE TABLE IF NOT EXISTS shipments (
    id                 BIGINT       PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    order_id           BIGINT       NOT NULL UNIQUE REFERENCES orders(id) ON DELETE CASCADE,
    carrier            VARCHAR(100),
    tracking_number    VARCHAR(100) UNIQUE,
    status             VARCHAR(30)  NOT NULL DEFAULT 'PREPARING'
                           CHECK (status IN ('PREPARING','PICKED_UP','IN_TRANSIT',
                                             'OUT_FOR_DELIVERY','DELIVERED','FAILED','RETURNED')),
    estimated_delivery DATE,
    created_at         TIMESTAMP    NOT NULL DEFAULT NOW(),
    updated_at         TIMESTAMP    NOT NULL DEFAULT NOW()
);
CREATE TRIGGER trg_shipments_updated_at
    BEFORE UPDATE ON shipments FOR EACH ROW EXECUTE FUNCTION fn_set_updated_at();

CREATE TABLE IF NOT EXISTS shipment_events (
    id          BIGINT      PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    shipment_id BIGINT      NOT NULL REFERENCES shipments(id) ON DELETE CASCADE,
    status      VARCHAR(30) NOT NULL,
    location    VARCHAR(255),
    note        TEXT,
    occurred_at TIMESTAMP   NOT NULL DEFAULT NOW()
);
CREATE INDEX IF NOT EXISTS idx_shipment_events_shipment ON shipment_events(shipment_id, occurred_at DESC);

-- ── SECTION 12: WISHLISTS ────────────────────────────────────
CREATE TABLE IF NOT EXISTS wishlists (
    id         BIGINT    PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    user_id    BIGINT    NOT NULL REFERENCES users(id)    ON DELETE CASCADE,
    product_id BIGINT    NOT NULL REFERENCES products(id) ON DELETE CASCADE,
    created_at TIMESTAMP NOT NULL DEFAULT NOW(),
    UNIQUE (user_id, product_id)
);
CREATE INDEX IF NOT EXISTS idx_wishlists_user    ON wishlists(user_id);
CREATE INDEX IF NOT EXISTS idx_wishlists_product ON wishlists(product_id);

-- ── SECTION 14: REPAIR SERVICE MARKETPLACE ───────────────────
CREATE TABLE IF NOT EXISTS technicians (
    id               BIGINT       PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    user_id          BIGINT       NOT NULL UNIQUE REFERENCES users(id) ON DELETE CASCADE,
    bio              TEXT,
    specialization   VARCHAR(30)  NOT NULL
                         CHECK (specialization IN ('Electronics','Electrical',
                                                   'Furniture','Appliances')),
    pickup_available BOOLEAN      NOT NULL DEFAULT FALSE,
    service_area     VARCHAR(255),
    website_url      TEXT,
    social_links     JSONB,
    level            VARCHAR(20)  NOT NULL DEFAULT 'Beginner'
                         CHECK (level IN ('Beginner','Verified','Expert')),
    rating_avg       DECIMAL(3,2) NOT NULL DEFAULT 0.00,
    completion_rate  DECIMAL(5,2) NOT NULL DEFAULT 0.00,
    created_at       TIMESTAMP    NOT NULL DEFAULT NOW(),
    updated_at       TIMESTAMP    NOT NULL DEFAULT NOW()
);
CREATE TRIGGER trg_technicians_updated_at
    BEFORE UPDATE ON technicians FOR EACH ROW EXECUTE FUNCTION fn_set_updated_at();

CREATE TABLE IF NOT EXISTS technician_level_history (
    id            BIGINT      PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    technician_id BIGINT      NOT NULL REFERENCES technicians(id) ON DELETE CASCADE,
    old_level     VARCHAR(20) NOT NULL,
    new_level     VARCHAR(20) NOT NULL,
    changed_at    TIMESTAMP   NOT NULL DEFAULT NOW()
);
CREATE INDEX IF NOT EXISTS idx_tech_level_history ON technician_level_history(technician_id, changed_at DESC);

CREATE TABLE IF NOT EXISTS technician_skills (
    id            BIGINT       PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    technician_id BIGINT       NOT NULL REFERENCES technicians(id) ON DELETE CASCADE,
    skill         VARCHAR(120) NOT NULL,
    created_at    TIMESTAMP    NOT NULL DEFAULT NOW()
);
CREATE INDEX IF NOT EXISTS idx_technician_skills_tech ON technician_skills(technician_id);

CREATE TABLE IF NOT EXISTS technician_availability (
    id            BIGINT    PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    technician_id BIGINT    NOT NULL REFERENCES technicians(id) ON DELETE CASCADE,
    day_of_week   SMALLINT  NOT NULL CHECK (day_of_week BETWEEN 0 AND 6),
    start_time    TIME      NOT NULL,
    end_time      TIME      NOT NULL,
    is_available  BOOLEAN   NOT NULL DEFAULT TRUE,
    created_at    TIMESTAMP NOT NULL DEFAULT NOW(),
    updated_at    TIMESTAMP NOT NULL DEFAULT NOW(),
    UNIQUE (technician_id, day_of_week),
    CHECK (end_time > start_time)
);
CREATE INDEX IF NOT EXISTS idx_tech_availability ON technician_availability(technician_id);
CREATE TRIGGER trg_tech_availability_updated_at
    BEFORE UPDATE ON technician_availability FOR EACH ROW EXECUTE FUNCTION fn_set_updated_at();

CREATE TABLE IF NOT EXISTS service_listings (
    id                BIGINT        PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    technician_id     BIGINT        NOT NULL REFERENCES technicians(id) ON DELETE CASCADE,
    category_id       BIGINT                 REFERENCES categories(id)  ON DELETE SET NULL,
    title             VARCHAR(255)  NOT NULL,
    description       TEXT,
    price_min_bdt     DECIMAL(12,2) NOT NULL CHECK (price_min_bdt >= 0),
    price_max_bdt     DECIMAL(12,2) NOT NULL CHECK (price_max_bdt >= price_min_bdt),
    availability_note VARCHAR(255),
    status            VARCHAR(20)   NOT NULL DEFAULT 'ACTIVE'
                          CHECK (status IN ('ACTIVE','INACTIVE')),
    created_at        TIMESTAMP     NOT NULL DEFAULT NOW(),
    updated_at        TIMESTAMP     NOT NULL DEFAULT NOW()
);
CREATE INDEX IF NOT EXISTS idx_service_listings_tech     ON service_listings(technician_id);
CREATE INDEX IF NOT EXISTS idx_service_listings_category ON service_listings(category_id);
CREATE INDEX IF NOT EXISTS idx_service_listings_status   ON service_listings(status);
CREATE TRIGGER trg_service_listings_updated_at
    BEFORE UPDATE ON service_listings FOR EACH ROW EXECUTE FUNCTION fn_set_updated_at();

CREATE TABLE IF NOT EXISTS repair_requests (
    id            BIGINT      PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    customer_id   BIGINT      NOT NULL REFERENCES users(id)      ON DELETE RESTRICT,
    address_id    BIGINT               REFERENCES addresses(id)   ON DELETE SET NULL,
    category_id   BIGINT               REFERENCES categories(id)  ON DELETE SET NULL,
    description   TEXT        NOT NULL,
    pickup_needed BOOLEAN     NOT NULL DEFAULT FALSE,
    status        VARCHAR(20) NOT NULL DEFAULT 'OPEN'
                      CHECK (status IN ('OPEN','QUOTED','BOOKED','COMPLETED','CANCELLED')),
    created_at    TIMESTAMP   NOT NULL DEFAULT NOW(),
    updated_at    TIMESTAMP   NOT NULL DEFAULT NOW()
);
CREATE INDEX IF NOT EXISTS idx_repair_requests_customer ON repair_requests(customer_id, status);
CREATE INDEX IF NOT EXISTS idx_repair_requests_status   ON repair_requests(status);
CREATE TRIGGER trg_repair_requests_updated_at
    BEFORE UPDATE ON repair_requests FOR EACH ROW EXECUTE FUNCTION fn_set_updated_at();

CREATE TABLE IF NOT EXISTS repair_media (
    id         BIGINT      PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    request_id BIGINT      NOT NULL REFERENCES repair_requests(id) ON DELETE CASCADE,
    media_url  TEXT        NOT NULL,
    media_type VARCHAR(10) NOT NULL CHECK (media_type IN ('IMAGE','VIDEO')),
    created_at TIMESTAMP   NOT NULL DEFAULT NOW()
);
CREATE INDEX IF NOT EXISTS idx_repair_media_request ON repair_media(request_id);

CREATE TABLE IF NOT EXISTS repair_quotes (
    id            BIGINT        PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    request_id    BIGINT        NOT NULL REFERENCES repair_requests(id) ON DELETE CASCADE,
    technician_id BIGINT        NOT NULL REFERENCES technicians(id)     ON DELETE CASCADE,
    quote_bdt     DECIMAL(12,2) NOT NULL CHECK (quote_bdt >= 0),
    plan          TEXT,
    status        VARCHAR(20)   NOT NULL DEFAULT 'SENT'
                      CHECK (status IN ('SENT','ACCEPTED','REJECTED')),
    created_at    TIMESTAMP     NOT NULL DEFAULT NOW(),
    updated_at    TIMESTAMP     NOT NULL DEFAULT NOW(),
    UNIQUE (request_id, technician_id)
);
CREATE INDEX IF NOT EXISTS idx_repair_quotes_request ON repair_quotes(request_id, status);
CREATE INDEX IF NOT EXISTS idx_repair_quotes_tech    ON repair_quotes(technician_id);
CREATE TRIGGER trg_repair_quotes_updated_at
    BEFORE UPDATE ON repair_quotes FOR EACH ROW EXECUTE FUNCTION fn_set_updated_at();

CREATE TABLE IF NOT EXISTS repair_bookings (
    id             BIGINT      PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    request_id     BIGINT      NOT NULL UNIQUE REFERENCES repair_requests(id) ON DELETE CASCADE,
    technician_id  BIGINT      NOT NULL REFERENCES technicians(id)            ON DELETE RESTRICT,
    scheduled_date DATE        NOT NULL,
    status         VARCHAR(20) NOT NULL DEFAULT 'CONFIRMED'
                       CHECK (status IN ('CONFIRMED','REJECTED','COMPLETED','CANCELLED')),
    created_at     TIMESTAMP   NOT NULL DEFAULT NOW(),
    updated_at     TIMESTAMP   NOT NULL DEFAULT NOW()
);
CREATE INDEX IF NOT EXISTS idx_repair_bookings_tech ON repair_bookings(technician_id, status);
CREATE TRIGGER trg_repair_bookings_updated_at
    BEFORE UPDATE ON repair_bookings FOR EACH ROW EXECUTE FUNCTION fn_set_updated_at();

CREATE TABLE IF NOT EXISTS service_completion (
    id           BIGINT    PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    booking_id   BIGINT    NOT NULL UNIQUE REFERENCES repair_bookings(id) ON DELETE CASCADE,
    notes        TEXT,
    completed_at TIMESTAMP NOT NULL DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS repair_payments (
    id               BIGINT        PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    booking_id       BIGINT        NOT NULL UNIQUE REFERENCES repair_bookings(id) ON DELETE CASCADE,
    amount_bdt       DECIMAL(12,2) NOT NULL CHECK (amount_bdt > 0),
    status           VARCHAR(20)   NOT NULL DEFAULT 'PENDING'
                         CHECK (status IN ('PENDING','PAID','FAILED','REFUNDED')),
    method           VARCHAR(50)   NOT NULL DEFAULT 'DUMMY',
    gateway_name     VARCHAR(50),
    transaction_ref  VARCHAR(100)  UNIQUE,
    gateway_response JSONB,
    paid_at          TIMESTAMP,
    created_at       TIMESTAMP     NOT NULL DEFAULT NOW(),
    updated_at       TIMESTAMP     NOT NULL DEFAULT NOW()
);
CREATE INDEX IF NOT EXISTS idx_repair_payments_booking ON repair_payments(booking_id);
CREATE INDEX IF NOT EXISTS idx_repair_payments_status  ON repair_payments(status);
CREATE TRIGGER trg_repair_payments_updated_at
    BEFORE UPDATE ON repair_payments FOR EACH ROW EXECUTE FUNCTION fn_set_updated_at();

CREATE TABLE IF NOT EXISTS technician_earnings (
    id               BIGINT        PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    technician_id    BIGINT        NOT NULL REFERENCES technicians(id)            ON DELETE CASCADE,
    booking_id       BIGINT        NOT NULL UNIQUE REFERENCES repair_bookings(id) ON DELETE CASCADE,
    gross_amount_bdt DECIMAL(12,2) NOT NULL,
    commission_rate  DECIMAL(5,2)  NOT NULL,
    commission_bdt   DECIMAL(12,2) NOT NULL,
    net_amount_bdt   DECIMAL(12,2) NOT NULL,
    status           VARCHAR(20)   NOT NULL DEFAULT 'PENDING'
                         CHECK (status IN ('PENDING','PAID','HELD')),
    created_at       TIMESTAMP     NOT NULL DEFAULT NOW(),
    updated_at       TIMESTAMP     NOT NULL DEFAULT NOW()
);
CREATE INDEX IF NOT EXISTS idx_technician_earnings_tech ON technician_earnings(technician_id, status);
CREATE TRIGGER trg_technician_earnings_updated_at
    BEFORE UPDATE ON technician_earnings FOR EACH ROW EXECUTE FUNCTION fn_set_updated_at();

-- ── SECTION 15: REVIEWS ──────────────────────────────────────
CREATE TABLE IF NOT EXISTS reviews (
    id            BIGINT    PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    reviewer_id   BIGINT    NOT NULL REFERENCES users(id)           ON DELETE CASCADE,
    reviewee_id   BIGINT    NOT NULL REFERENCES users(id)           ON DELETE CASCADE,
    product_id    BIGINT             REFERENCES products(id)        ON DELETE SET NULL,
    order_item_id BIGINT             REFERENCES order_items(id)     ON DELETE SET NULL,
    booking_id    BIGINT             REFERENCES repair_bookings(id) ON DELETE SET NULL,
    rating        INT       NOT NULL CHECK (rating BETWEEN 1 AND 5),
    comment       TEXT,
    created_at    TIMESTAMP NOT NULL DEFAULT NOW(),
    CHECK (reviewer_id <> reviewee_id)
);
CREATE INDEX IF NOT EXISTS idx_reviews_reviewee   ON reviews(reviewee_id);
CREATE INDEX IF NOT EXISTS idx_reviews_product    ON reviews(product_id);
CREATE INDEX IF NOT EXISTS idx_reviews_reviewer   ON reviews(reviewer_id);
CREATE INDEX IF NOT EXISTS idx_reviews_booking    ON reviews(booking_id);
CREATE INDEX IF NOT EXISTS idx_reviews_order_item ON reviews(order_item_id);

-- ── SECTION 16: AUCTION SYSTEM ───────────────────────────────
CREATE TABLE IF NOT EXISTS auctions (
    id             BIGINT       PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    vendor_id      BIGINT       NOT NULL REFERENCES users(id) ON DELETE RESTRICT,
    title          VARCHAR(255) NOT NULL,
    type           VARCHAR(20)  NOT NULL
                       CHECK (type IN ('STANDARD','FLASH','REVERSE','RESERVE')),
    status         VARCHAR(20)  NOT NULL DEFAULT 'CREATED'
                       CHECK (status IN ('CREATED','APPROVED','PREPARING','ACTIVE',
                                         'EXTENDED','CLOSED','COMPLETED','REJECTED')),
    start_time     TIMESTAMP    NOT NULL,
    end_time       TIMESTAMP    NOT NULL,
    terms_accepted BOOLEAN      NOT NULL DEFAULT FALSE,
    created_at     TIMESTAMP    NOT NULL DEFAULT NOW(),
    updated_at     TIMESTAMP    NOT NULL DEFAULT NOW(),
    CHECK (end_time > start_time)
);
CREATE INDEX IF NOT EXISTS idx_auctions_vendor_status ON auctions(vendor_id, status);
CREATE INDEX IF NOT EXISTS idx_auctions_status_time   ON auctions(status, start_time);
CREATE TRIGGER trg_auctions_updated_at
    BEFORE UPDATE ON auctions FOR EACH ROW EXECUTE FUNCTION fn_set_updated_at();

CREATE TABLE IF NOT EXISTS auction_lots (
    id                         BIGINT        PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    auction_id                 BIGINT        NOT NULL REFERENCES auctions(id)    ON DELETE CASCADE,
    category_id                BIGINT                 REFERENCES categories(id)  ON DELETE SET NULL,
    title                      VARCHAR(255)  NOT NULL,
    description                TEXT,
    condition_note             VARCHAR(100),
    starting_price_bdt         DECIMAL(12,2) NOT NULL CHECK (starting_price_bdt >= 0),
    reserve_price_bdt          DECIMAL(12,2)           CHECK (reserve_price_bdt >= 0),
    current_bid_bdt            DECIMAL(12,2) NOT NULL DEFAULT 0.00,
    min_bid_increment_bdt      DECIMAL(12,2) NOT NULL DEFAULT 10.00
                                   CHECK (min_bid_increment_bdt > 0),
    extension_duration_minutes INT           NOT NULL DEFAULT 5,
    extensions_count           INT           NOT NULL DEFAULT 0,
    max_extensions             INT           NOT NULL DEFAULT 3,
    status                     VARCHAR(20)   NOT NULL DEFAULT 'PREPARING'
                                   CHECK (status IN ('PREPARING','ACTIVE','EXTENDED','CLOSED')),
    created_at                 TIMESTAMP     NOT NULL DEFAULT NOW(),
    updated_at                 TIMESTAMP     NOT NULL DEFAULT NOW()
);
CREATE INDEX IF NOT EXISTS idx_auction_lots_auction  ON auction_lots(auction_id);
CREATE INDEX IF NOT EXISTS idx_auction_lots_status   ON auction_lots(status);
CREATE INDEX IF NOT EXISTS idx_auction_lots_category ON auction_lots(category_id);
CREATE TRIGGER trg_auction_lots_updated_at
    BEFORE UPDATE ON auction_lots FOR EACH ROW EXECUTE FUNCTION fn_set_updated_at();

CREATE TABLE IF NOT EXISTS auction_images (
    id         BIGINT    PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    lot_id     BIGINT    NOT NULL REFERENCES auction_lots(id) ON DELETE CASCADE,
    image_url  TEXT      NOT NULL,
    sort_order INT       NOT NULL DEFAULT 0,
    created_at TIMESTAMP NOT NULL DEFAULT NOW()
);
CREATE INDEX IF NOT EXISTS idx_auction_images_lot ON auction_images(lot_id, sort_order);

CREATE TABLE IF NOT EXISTS bids (
    id         BIGINT        PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    lot_id     BIGINT        NOT NULL REFERENCES auction_lots(id) ON DELETE CASCADE,
    bidder_id  BIGINT        NOT NULL REFERENCES users(id)        ON DELETE RESTRICT,
    amount_bdt DECIMAL(12,2) NOT NULL CHECK (amount_bdt > 0),
    is_winning BOOLEAN       NOT NULL DEFAULT FALSE,
    created_at TIMESTAMP     NOT NULL DEFAULT NOW()
);
CREATE INDEX IF NOT EXISTS idx_bids_lot_amount ON bids(lot_id, amount_bdt DESC);
CREATE INDEX IF NOT EXISTS idx_bids_bidder_lot ON bids(bidder_id, lot_id);

CREATE TABLE IF NOT EXISTS auction_watchlist (
    id         BIGINT    PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    user_id    BIGINT    NOT NULL REFERENCES users(id)        ON DELETE CASCADE,
    lot_id     BIGINT    NOT NULL REFERENCES auction_lots(id) ON DELETE CASCADE,
    created_at TIMESTAMP NOT NULL DEFAULT NOW(),
    UNIQUE (user_id, lot_id)
);
CREATE INDEX IF NOT EXISTS idx_auction_watchlist_user ON auction_watchlist(user_id);
CREATE INDEX IF NOT EXISTS idx_auction_watchlist_lot  ON auction_watchlist(lot_id);

CREATE TABLE IF NOT EXISTS auction_winners (
    id                BIGINT        PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    lot_id            BIGINT        NOT NULL UNIQUE REFERENCES auction_lots(id) ON DELETE CASCADE,
    winner_id         BIGINT        NOT NULL REFERENCES users(id)               ON DELETE RESTRICT,
    winning_bid_id    BIGINT        NOT NULL UNIQUE REFERENCES bids(id)         ON DELETE RESTRICT,
    final_price_bdt   DECIMAL(12,2) NOT NULL,
    reserve_met       BOOLEAN       NOT NULL DEFAULT TRUE,
    payment_status    VARCHAR(20)   NOT NULL DEFAULT 'PENDING'
                          CHECK (payment_status IN ('PENDING','PAID','FAILED','WAIVED')),
    payment_deadline  TIMESTAMP     NOT NULL,
    paid_at           TIMESTAMP,
    non_payment_count INT           NOT NULL DEFAULT 0,
    created_at        TIMESTAMP     NOT NULL DEFAULT NOW(),
    updated_at        TIMESTAMP     NOT NULL DEFAULT NOW()
);
CREATE INDEX IF NOT EXISTS idx_auction_winners_winner  ON auction_winners(winner_id);
CREATE INDEX IF NOT EXISTS idx_auction_winners_pending ON auction_winners(payment_status)
    WHERE payment_status = 'PENDING';
CREATE TRIGGER trg_auction_winners_updated_at
    BEFORE UPDATE ON auction_winners FOR EACH ROW EXECUTE FUNCTION fn_set_updated_at();

CREATE TABLE IF NOT EXISTS auction_payments (
    id                BIGINT        PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    auction_winner_id BIGINT        NOT NULL UNIQUE REFERENCES auction_winners(id) ON DELETE CASCADE,
    amount_bdt        DECIMAL(12,2) NOT NULL CHECK (amount_bdt > 0),
    status            VARCHAR(20)   NOT NULL DEFAULT 'PENDING'
                          CHECK (status IN ('PENDING','PAID','FAILED','REFUNDED')),
    method            VARCHAR(50)   NOT NULL DEFAULT 'DUMMY',
    gateway_name      VARCHAR(50),
    transaction_ref   VARCHAR(100)  UNIQUE,
    gateway_response  JSONB,
    paid_at           TIMESTAMP,
    created_at        TIMESTAMP     NOT NULL DEFAULT NOW(),
    updated_at        TIMESTAMP     NOT NULL DEFAULT NOW()
);
CREATE INDEX IF NOT EXISTS idx_auction_payments_winner ON auction_payments(auction_winner_id);
CREATE INDEX IF NOT EXISTS idx_auction_payments_status ON auction_payments(status);
CREATE TRIGGER trg_auction_payments_updated_at
    BEFORE UPDATE ON auction_payments FOR EACH ROW EXECUTE FUNCTION fn_set_updated_at();

CREATE TABLE IF NOT EXISTS auction_approvals (
    id         BIGINT      PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    auction_id BIGINT      NOT NULL REFERENCES auctions(id) ON DELETE CASCADE,
    admin_id   BIGINT      NOT NULL REFERENCES users(id)    ON DELETE RESTRICT,
    status     VARCHAR(20) NOT NULL CHECK (status IN ('APPROVED','REJECTED')),
    notes      TEXT,
    decided_at TIMESTAMP   NOT NULL DEFAULT NOW()
);
CREATE INDEX IF NOT EXISTS idx_auction_approvals_auction ON auction_approvals(auction_id);

CREATE TABLE IF NOT EXISTS auction_status_log (
    id         BIGINT      PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    auction_id BIGINT      NOT NULL REFERENCES auctions(id) ON DELETE CASCADE,
    old_status VARCHAR(30) NOT NULL,
    new_status VARCHAR(30) NOT NULL,
    changed_by BIGINT               REFERENCES users(id) ON DELETE SET NULL,
    changed_at TIMESTAMP   NOT NULL DEFAULT NOW()
);
CREATE INDEX IF NOT EXISTS idx_auction_status_log ON auction_status_log(auction_id, changed_at DESC);

-- ── SECTION 17: TRUST SCORES ─────────────────────────────────
CREATE TABLE IF NOT EXISTS trust_scores (
    user_id    BIGINT       PRIMARY KEY REFERENCES users(id) ON DELETE CASCADE,
    score      DECIMAL(5,2) NOT NULL DEFAULT 50.00 CHECK (score BETWEEN 0 AND 100),
    created_at TIMESTAMP    NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMP    NOT NULL DEFAULT NOW()
);
CREATE TRIGGER trg_trust_scores_updated_at
    BEFORE UPDATE ON trust_scores FOR EACH ROW EXECUTE FUNCTION fn_set_updated_at();

CREATE TABLE IF NOT EXISTS trust_events (
    id         BIGINT       PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    user_id    BIGINT       NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    event_type VARCHAR(100) NOT NULL,
    delta      DECIMAL(5,2) NOT NULL,
    note       TEXT,
    created_at TIMESTAMP    NOT NULL DEFAULT NOW()
);
CREATE INDEX IF NOT EXISTS idx_trust_events_user ON trust_events(user_id, created_at DESC);

-- ── SECTION 18: FRAUD DETECTION ──────────────────────────────
CREATE TABLE IF NOT EXISTS fraud_flags (
    id          BIGINT       PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    user_id     BIGINT       NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    flagged_by  BIGINT                REFERENCES users(id) ON DELETE SET NULL,
    reason      VARCHAR(255) NOT NULL,
    status      VARCHAR(20)  NOT NULL DEFAULT 'OPEN'
                    CHECK (status IN ('OPEN','REVIEWED','RESOLVED')),
    resolved_by BIGINT                REFERENCES users(id) ON DELETE SET NULL,
    resolved_at TIMESTAMP,
    created_at  TIMESTAMP    NOT NULL DEFAULT NOW(),
    updated_at  TIMESTAMP    NOT NULL DEFAULT NOW()
);
CREATE INDEX IF NOT EXISTS idx_fraud_flags_user_status ON fraud_flags(user_id, status);
CREATE INDEX IF NOT EXISTS idx_fraud_flags_open        ON fraud_flags(status) WHERE status = 'OPEN';
CREATE TRIGGER trg_fraud_flags_updated_at
    BEFORE UPDATE ON fraud_flags FOR EACH ROW EXECUTE FUNCTION fn_set_updated_at();

CREATE TABLE IF NOT EXISTS fraud_events (
    id         BIGINT       PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    user_id    BIGINT       NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    event_type VARCHAR(100) NOT NULL,
    details    TEXT,
    severity   VARCHAR(20)  NOT NULL DEFAULT 'LOW'
                   CHECK (severity IN ('LOW','MEDIUM','HIGH','CRITICAL')),
    created_at TIMESTAMP    NOT NULL DEFAULT NOW()
);
CREATE INDEX IF NOT EXISTS idx_fraud_events_user     ON fraud_events(user_id);
CREATE INDEX IF NOT EXISTS idx_fraud_events_severity ON fraud_events(severity, created_at DESC);

CREATE TABLE IF NOT EXISTS reports (
    id          BIGINT      PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    reporter_id BIGINT      NOT NULL REFERENCES users(id) ON DELETE RESTRICT,
    reported_id BIGINT      NOT NULL REFERENCES users(id) ON DELETE RESTRICT,
    entity_type VARCHAR(60),
    entity_id   BIGINT,
    reason      TEXT        NOT NULL,
    status      VARCHAR(20) NOT NULL DEFAULT 'OPEN'
                    CHECK (status IN ('OPEN','REVIEWED','RESOLVED','DISMISSED')),
    admin_note  TEXT,
    resolved_at TIMESTAMP,
    created_at  TIMESTAMP   NOT NULL DEFAULT NOW(),
    updated_at  TIMESTAMP   NOT NULL DEFAULT NOW(),
    CHECK (reporter_id <> reported_id)
);
CREATE INDEX IF NOT EXISTS idx_reports_reported ON reports(reported_id);
CREATE INDEX IF NOT EXISTS idx_reports_reporter ON reports(reporter_id);
CREATE INDEX IF NOT EXISTS idx_reports_open     ON reports(status) WHERE status = 'OPEN';
CREATE TRIGGER trg_reports_updated_at
    BEFORE UPDATE ON reports FOR EACH ROW EXECUTE FUNCTION fn_set_updated_at();

-- ── SECTION 19: BIDDER REPUTATION ────────────────────────────
CREATE TABLE IF NOT EXISTS bidder_reputation (
    user_id              BIGINT       PRIMARY KEY REFERENCES users(id) ON DELETE CASCADE,
    auctions_won         INT          NOT NULL DEFAULT 0,
    auctions_entered     INT          NOT NULL DEFAULT 0,
    win_rate             DECIMAL(5,2) NOT NULL DEFAULT 0.00,
    payment_success_rate DECIMAL(5,2) NOT NULL DEFAULT 0.00,
    cancellation_rate    DECIMAL(5,2) NOT NULL DEFAULT 0.00,
    created_at           TIMESTAMP    NOT NULL DEFAULT NOW(),
    updated_at           TIMESTAMP    NOT NULL DEFAULT NOW()
);
CREATE TRIGGER trg_bidder_reputation_updated_at
    BEFORE UPDATE ON bidder_reputation FOR EACH ROW EXECUTE FUNCTION fn_set_updated_at();

CREATE TABLE IF NOT EXISTS bidder_restrictions (
    id         BIGINT    PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    vendor_id  BIGINT    NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    bidder_id  BIGINT    NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    reason     VARCHAR(255),
    created_at TIMESTAMP NOT NULL DEFAULT NOW(),
    UNIQUE (vendor_id, bidder_id),
    CHECK (vendor_id <> bidder_id)
);
CREATE INDEX IF NOT EXISTS idx_bidder_restrictions_vendor ON bidder_restrictions(vendor_id);
CREATE INDEX IF NOT EXISTS idx_bidder_restrictions_bidder ON bidder_restrictions(bidder_id);

-- ── SECTION 20: RETURNS ──────────────────────────────────────
CREATE TABLE IF NOT EXISTS returns (
    id                BIGINT        PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    order_item_id     BIGINT        NOT NULL REFERENCES order_items(id) ON DELETE CASCADE,
    customer_id       BIGINT        NOT NULL REFERENCES users(id)       ON DELETE RESTRICT,
    reason            TEXT          NOT NULL,
    status            VARCHAR(20)   NOT NULL DEFAULT 'OPEN'
                          CHECK (status IN ('OPEN','APPROVED','REJECTED','COMPLETED','CANCELLED')),
    admin_note        TEXT,
    refund_amount_bdt DECIMAL(12,2),
    resolved_at       TIMESTAMP,
    created_at        TIMESTAMP     NOT NULL DEFAULT NOW(),
    updated_at        TIMESTAMP     NOT NULL DEFAULT NOW()
);
CREATE INDEX IF NOT EXISTS idx_returns_customer   ON returns(customer_id);
CREATE INDEX IF NOT EXISTS idx_returns_order_item ON returns(order_item_id);
CREATE INDEX IF NOT EXISTS idx_returns_open       ON returns(status) WHERE status = 'OPEN';
CREATE TRIGGER trg_returns_updated_at
    BEFORE UPDATE ON returns FOR EACH ROW EXECUTE FUNCTION fn_set_updated_at();

-- ── SECTION 21: CHAT & MESSAGING ─────────────────────────────
CREATE TABLE IF NOT EXISTS conversations (
    id         BIGINT    PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    created_at TIMESTAMP NOT NULL DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS conversation_members (
    conversation_id BIGINT    NOT NULL REFERENCES conversations(id) ON DELETE CASCADE,
    user_id         BIGINT    NOT NULL REFERENCES users(id)         ON DELETE CASCADE,
    joined_at       TIMESTAMP NOT NULL DEFAULT NOW(),
    PRIMARY KEY (conversation_id, user_id)
);
CREATE INDEX IF NOT EXISTS idx_conversation_members_user ON conversation_members(user_id);

CREATE TABLE IF NOT EXISTS messages (
    id              BIGINT    PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    conversation_id BIGINT    NOT NULL REFERENCES conversations(id) ON DELETE CASCADE,
    sender_id       BIGINT    NOT NULL REFERENCES users(id)         ON DELETE RESTRICT,
    body            TEXT      NOT NULL,
    is_read         BOOLEAN   NOT NULL DEFAULT FALSE,
    created_at      TIMESTAMP NOT NULL DEFAULT NOW()
);
CREATE INDEX IF NOT EXISTS idx_messages_conversation ON messages(conversation_id, created_at DESC);
CREATE INDEX IF NOT EXISTS idx_messages_sender       ON messages(sender_id);

-- ── SECTION 22: NOTIFICATIONS ────────────────────────────────
CREATE TABLE IF NOT EXISTS notifications (
    id          BIGINT       PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    user_id     BIGINT       NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    type        VARCHAR(60)  NOT NULL,
    title       VARCHAR(120) NOT NULL,
    body        TEXT         NOT NULL,
    entity_type VARCHAR(60),
    entity_id   BIGINT,
    is_read     BOOLEAN      NOT NULL DEFAULT FALSE,
    created_at  TIMESTAMP    NOT NULL DEFAULT NOW(),
    updated_at  TIMESTAMP    NOT NULL DEFAULT NOW()
);
CREATE INDEX IF NOT EXISTS idx_notifications_user_read ON notifications(user_id, is_read, created_at DESC);
CREATE TRIGGER trg_notifications_updated_at
    BEFORE UPDATE ON notifications FOR EACH ROW EXECUTE FUNCTION fn_set_updated_at();

CREATE TABLE IF NOT EXISTS notification_subscriptions (
    id          BIGINT      PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    user_id     BIGINT      NOT NULL REFERENCES users(id)      ON DELETE CASCADE,
    event_type  VARCHAR(60) NOT NULL,
    category_id BIGINT               REFERENCES categories(id) ON DELETE CASCADE,
    created_at  TIMESTAMP   NOT NULL DEFAULT NOW(),
    UNIQUE (user_id, event_type, category_id)
);
CREATE INDEX IF NOT EXISTS idx_notification_subs_user ON notification_subscriptions(user_id);

-- ── SECTION 23: SEED DATA ────────────────────────────────────
INSERT INTO roles (name) VALUES
    ('ADMIN'),('VENDOR'),('CUSTOMER'),('TECHNICIAN')
ON CONFLICT (name) DO NOTHING;

-- Seed admin user (admin@gmail.com / admin)
INSERT INTO users (email, password_hash, display_name, status)
VALUES ('admin@gmail.com', '$2a$12$wga1GGdKNF8bX58KuqrM5.IlcWvKJW6CqjTL4IQubBvrsvueglANS', 'Admin', 'ACTIVE')
ON CONFLICT (email) DO NOTHING;

INSERT INTO user_roles (user_id, role_id)
SELECT u.id, r.id FROM users u
JOIN roles r ON r.name = 'ADMIN'
WHERE u.email = 'admin@gmail.com'
ON CONFLICT DO NOTHING;

INSERT INTO trust_scores (user_id, score)
SELECT u.id, 50.00 FROM users u
WHERE u.email = 'admin@gmail.com'
ON CONFLICT (user_id) DO NOTHING;

INSERT INTO condition_levels (label, sort_order) VALUES
    ('Like New',1),('Good',2),('Fair',3),('Needs Repair',4)
ON CONFLICT (label) DO NOTHING;

INSERT INTO categories (name, slug, sort_order) VALUES
    ('Electronics','electronics',1),
    ('Appliances','appliances',2),
    ('Audio & Video','audio-video',3),
    ('Computers','computers',4),
    ('Furniture','furniture',5),
    ('Vehicles','vehicles',6),
    ('Clothing','clothing',7),
    ('Books','books',8),
    ('Sports','sports',9),
    ('Miscellaneous','miscellaneous',10)
ON CONFLICT (slug) DO NOTHING;

INSERT INTO platform_settings (key, value, data_type, description) VALUES
    ('vendor.commission_rate',         '10.00', 'DECIMAL', 'Platform cut % on vendor product sales'),
    ('technician.commission_rate',     '8.00',  'DECIMAL', 'Platform cut % on repair payments'),
    ('trust.initial_score',            '50.00', 'DECIMAL', 'Starting trust score for new users'),
    ('trust.low_score_threshold',      '30.00', 'DECIMAL', 'Score below this restricts features'),
    ('trust.high_score_threshold',     '80.00', 'DECIMAL', 'Score above this unlocks badges'),
    ('trust.ban_threshold',            '10.00', 'DECIMAL', 'Score below this triggers auto review'),
    ('technician.verified_threshold',  '10',    'INTEGER', 'Jobs to reach Verified level'),
    ('technician.expert_threshold',    '50',    'INTEGER', 'Jobs to reach Expert level'),
    ('auction.default_bid_increment',  '10.00', 'DECIMAL', 'Default min bid increment in BDT'),
    ('auction.extension_minutes',      '5',     'INTEGER', 'Minutes added per auto-extension'),
    ('auction.max_extensions',         '3',     'INTEGER', 'Max auto-extensions per lot'),
    ('auction.payment_deadline_hours', '48',    'INTEGER', 'Hours winner has to pay'),
    ('auction.nonpayment_ban_count',   '2',     'INTEGER', 'Non-payments before bidder ban'),
    ('cart.expiry_hours',              '24',    'INTEGER', 'Cart idle expiry in hours'),
    ('coupon.max_uses_default',        '1',     'INTEGER', 'Default max uses per coupon per user'),
    ('offer.default_expiry_hours',     '24',    'INTEGER', 'Hours before used-item offer expires'),
    ('shipping.default_fee_bdt',       '60.00', 'DECIMAL', 'Default flat shipping fee in BDT')
ON CONFLICT (key) DO NOTHING;
